import { createClient } from "@/lib/supabase/client";
import type { ServiceResponse } from "@/types/api.types";
import type {
    Customer,
    CustomerLedgerEntry,
    CreditNote,
    CustomerCreditSummary,
    CreateCustomerRequest,
    UpdateCustomerRequest,
    CreateLedgerEntryRequest,
    RecordPaymentRequest,
    AdjustLoyaltyPointsRequest,
    BlacklistCustomerRequest,
    CustomerFilters,
    CustomerPagination,
    CustomerListResponse,
    CustomerDashboardStats,
    CustomerType,
} from "@/types/customers.types";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const getClient = () => createClient() as any;

// ============================================================================
// CUSTOMER SERVICE
// All CRUD operations for customers, ledger, credit notes, loyalty
// ============================================================================

export const customerService = {
    // ========================================================================
    // CUSTOMER CRUD
    // ========================================================================

    /**
     * Create a new customer.
     * `customer_code` is auto-generated by the `generate_customer_code()` trigger.
     */
    create: async (
        storeId: string,
        data: CreateCustomerRequest
    ): Promise<ServiceResponse<Customer>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;
            if (!user) return { data: null, error: "Not authenticated" };

            const { data: customer, error } = await getClient()
                .from("customers")
                .insert({
                    ...data,
                    store_id: storeId,
                    created_by: user.id,
                } as never)
                .select()
                .single();

            if (error) {
                // Handle unique constraint violation on phone
                if (error.code === "23505" && error.message.includes("phone")) {
                    return { data: null, error: "A customer with this phone number already exists in your store" };
                }
                return { data: null, error: error.message };
            }

            return { data: customer as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to create customer" };
        }
    },

    /**
     * Get a customer by ID.
     */
    getById: async (
        storeId: string,
        customerId: string
    ): Promise<ServiceResponse<Customer>> => {
        try {
            const { data: customer, error } = await getClient()
                .from("customers")
                .select("*")
                .eq("id", customerId)
                .eq("store_id", storeId)
                .single();

            if (error) return { data: null, error: error.message };
            if (!customer) return { data: null, error: "Customer not found" };

            return { data: customer as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to fetch customer" };
        }
    },

    /**
     * Get paginated list of customers with filters.
     * Uses full-text GIN index on `name` for search, and
     * `idx_customers_store_phone` for phone lookups.
     */
    getList: async (
        storeId: string,
        filters?: CustomerFilters,
        pagination?: CustomerPagination
    ): Promise<ServiceResponse<CustomerListResponse>> => {
        try {
            const page = pagination?.page ?? 1;
            const limit = pagination?.limit ?? 20;
            const sortBy = pagination?.sort_by ?? "created_at";
            const sortOrder = pagination?.sort_order ?? "desc";
            const offset = (page - 1) * limit;

            let query = getClient()
                .from("customers")
                .select("*", { count: "exact" })
                .eq("store_id", storeId);

            // Apply filters
            if (filters) {
                if (filters.customer_type) {
                    query = query.eq("customer_type", filters.customer_type);
                }
                if (filters.is_active !== undefined) {
                    query = query.eq("is_active", filters.is_active);
                }
                if (filters.is_blacklisted !== undefined) {
                    query = query.eq("is_blacklisted", filters.is_blacklisted);
                }
                if (filters.is_credit_allowed !== undefined) {
                    query = query.eq("is_credit_allowed", filters.is_credit_allowed);
                }
                if (filters.has_outstanding === true) {
                    query = query.gt("outstanding_balance", 0);
                } else if (filters.has_outstanding === false) {
                    query = query.lte("outstanding_balance", 0);
                }
                if (filters.city) {
                    query = query.ilike("city", filters.city);
                }
                if (filters.state) {
                    query = query.ilike("state", filters.state);
                }
                if (filters.tags && filters.tags.length > 0) {
                    query = query.overlaps("tags", filters.tags);
                }
                if (filters.min_purchases !== undefined) {
                    query = query.gte("total_purchases", filters.min_purchases);
                }
                if (filters.max_purchases !== undefined) {
                    query = query.lte("total_purchases", filters.max_purchases);
                }
                if (filters.min_loyalty_points !== undefined) {
                    query = query.gte("loyalty_points", filters.min_loyalty_points);
                }
                if (filters.search) {
                    // Leverage idx_customers_store_phone and idx_customers_name (GIN)
                    query = query.or(
                        `name.ilike.%${filters.search}%,` +
                        `phone.ilike.%${filters.search}%,` +
                        `customer_code.ilike.%${filters.search}%,` +
                        `email.ilike.%${filters.search}%,` +
                        `company_name.ilike.%${filters.search}%`
                    );
                }
            }

            // Apply sorting and pagination
            query = query
                .order(sortBy, { ascending: sortOrder === "asc" })
                .range(offset, offset + limit - 1);

            const { data, error, count } = await query;

            if (error) return { data: null, error: error.message };

            const total = count ?? 0;
            const totalPages = Math.ceil(total / limit);

            return {
                data: {
                    customers: (data ?? []) as unknown as Customer[],
                    total,
                    page,
                    limit,
                    total_pages: totalPages,
                },
                error: null,
            };
        } catch {
            return { data: null, error: "Failed to fetch customers" };
        }
    },

    /**
     * Update a customer.
     */
    update: async (
        storeId: string,
        customerId: string,
        data: UpdateCustomerRequest
    ): Promise<ServiceResponse<Customer>> => {
        try {
            const { data: updated, error } = await getClient()
                .from("customers")
                .update(data as never)
                .eq("id", customerId)
                .eq("store_id", storeId)
                .select()
                .single();

            if (error) {
                if (error.code === "23505" && error.message.includes("phone")) {
                    return { data: null, error: "A customer with this phone number already exists in your store" };
                }
                return { data: null, error: error.message };
            }

            return { data: updated as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to update customer" };
        }
    },

    /**
     * Soft-delete a customer (set is_active = false).
     */
    deactivate: async (
        storeId: string,
        customerId: string
    ): Promise<ServiceResponse<Customer>> => {
        return customerService.update(storeId, customerId, { is_active: false });
    },

    /**
     * Reactivate a deactivated customer.
     */
    reactivate: async (
        storeId: string,
        customerId: string
    ): Promise<ServiceResponse<Customer>> => {
        return customerService.update(storeId, customerId, { is_active: true });
    },

    /**
     * Hard-delete a customer (only if no transactions exist).
     * Use with caution — prefer deactivate for data integrity.
     */
    delete: async (
        storeId: string,
        customerId: string
    ): Promise<ServiceResponse<null>> => {
        try {
            // Check for ledger entries before delete
            const { count } = await getClient()
                .from("customer_ledger")
                .select("id", { count: "exact", head: true })
                .eq("customer_id", customerId)
                .eq("store_id", storeId);

            if (count && count > 0) {
                return {
                    data: null,
                    error: "Cannot delete customer with existing ledger entries. Use deactivate instead.",
                };
            }

            const { error } = await getClient()
                .from("customers")
                .delete()
                .eq("id", customerId)
                .eq("store_id", storeId);

            if (error) return { data: null, error: error.message };
            return { data: null, error: null };
        } catch {
            return { data: null, error: "Failed to delete customer" };
        }
    },

    // ========================================================================
    // POS QUICK LOOKUP — Customer lookup is the first thing a cashier does
    // ========================================================================

    /**
     * Lookup customer by phone number (POS primary lookup).
     * Uses `idx_customers_store_phone` index for fast retrieval.
     */
    getByPhone: async (
        storeId: string,
        phone: string
    ): Promise<ServiceResponse<Customer>> => {
        try {
            const { data: customer, error } = await getClient()
                .from("customers")
                .select("*")
                .eq("store_id", storeId)
                .eq("phone", phone)
                .single();

            if (error) {
                if (error.code === "PGRST116") {
                    return { data: null, error: "No customer found with this phone number" };
                }
                return { data: null, error: error.message };
            }

            return { data: customer as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to lookup customer by phone" };
        }
    },

    /**
     * Lookup customer by customer code (e.g. STORE1-CUST0001).
     */
    getByCode: async (
        storeId: string,
        code: string
    ): Promise<ServiceResponse<Customer>> => {
        try {
            const { data: customer, error } = await getClient()
                .from("customers")
                .select("*")
                .eq("store_id", storeId)
                .eq("customer_code", code)
                .single();

            if (error) {
                if (error.code === "PGRST116") {
                    return { data: null, error: "No customer found with this code" };
                }
                return { data: null, error: error.message };
            }

            return { data: customer as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to lookup customer by code" };
        }
    },

    /**
     * Quick search customers for POS autocomplete.
     * Searches across name, phone, code — returns max `limit` results.
     */
    quickSearch: async (
        storeId: string,
        query: string,
        limit: number = 10
    ): Promise<ServiceResponse<Customer[]>> => {
        try {
            if (!query.trim()) return { data: [], error: null };

            const { data, error } = await getClient()
                .from("customers")
                .select("*")
                .eq("store_id", storeId)
                .eq("is_active", true)
                .or(
                    `name.ilike.%${query}%,` +
                    `phone.ilike.%${query}%,` +
                    `customer_code.ilike.%${query}%`
                )
                .order("total_visits", { ascending: false })
                .limit(limit);

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as Customer[], error: null };
        } catch {
            return { data: null, error: "Failed to search customers" };
        }
    },

    /**
     * Check if a phone number is unique within the store (for form validation).
     */
    isPhoneUnique: async (
        storeId: string,
        phone: string,
        excludeCustomerId?: string
    ): Promise<ServiceResponse<boolean>> => {
        try {
            let query = getClient()
                .from("customers")
                .select("id", { count: "exact", head: true })
                .eq("store_id", storeId)
                .eq("phone", phone);

            if (excludeCustomerId) {
                query = query.neq("id", excludeCustomerId);
            }

            const { count, error } = await query;

            if (error) return { data: null, error: error.message };
            return { data: (count ?? 0) === 0, error: null };
        } catch {
            return { data: null, error: "Failed to check phone uniqueness" };
        }
    },

    // ========================================================================
    // BLACKLIST
    // ========================================================================

    /**
     * Blacklist or unblacklist a customer.
     */
    toggleBlacklist: async (
        storeId: string,
        customerId: string,
        data: BlacklistCustomerRequest
    ): Promise<ServiceResponse<Customer>> => {
        try {
            const updateData: Record<string, unknown> = {
                is_blacklisted: data.is_blacklisted,
            };

            if (data.is_blacklisted) {
                updateData.blacklist_reason = data.blacklist_reason ?? null;
                updateData.is_active = false; // Blacklisted customers are also deactivated
            } else {
                updateData.blacklist_reason = null;
            }

            const { data: updated, error } = await getClient()
                .from("customers")
                .update(updateData as never)
                .eq("id", customerId)
                .eq("store_id", storeId)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: updated as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to update blacklist status" };
        }
    },

    // ========================================================================
    // CUSTOMER LEDGER
    // ========================================================================

    /**
     * Get ledger entries for a customer, ordered by entry_date DESC.
     * Uses `idx_customer_ledger_customer` index.
     */
    getLedger: async (
        storeId: string,
        customerId: string,
        page: number = 1,
        limit: number = 50
    ): Promise<ServiceResponse<{ entries: CustomerLedgerEntry[]; total: number }>> => {
        try {
            const offset = (page - 1) * limit;

            const { data, error, count } = await getClient()
                .from("customer_ledger")
                .select("*", { count: "exact" })
                .eq("customer_id", customerId)
                .eq("store_id", storeId)
                .order("entry_date", { ascending: false })
                .order("created_at", { ascending: false })
                .range(offset, offset + limit - 1);

            if (error) return { data: null, error: error.message };

            return {
                data: {
                    entries: (data ?? []) as unknown as CustomerLedgerEntry[],
                    total: count ?? 0,
                },
                error: null,
            };
        } catch {
            return { data: null, error: "Failed to fetch customer ledger" };
        }
    },

    /**
     * Create a manual ledger entry (e.g. opening balance or adjustment).
     * For sale credit and payments, these are created automatically by DB triggers.
     */
    createLedgerEntry: async (
        storeId: string,
        data: CreateLedgerEntryRequest
    ): Promise<ServiceResponse<CustomerLedgerEntry>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;
            if (!user) return { data: null, error: "Not authenticated" };

            const now = new Date();
            const entryDate = now.toISOString().split("T")[0];
            const entryTime = now.toTimeString().split(" ")[0];

            const { data: entry, error } = await getClient()
                .from("customer_ledger")
                .insert({
                    store_id: storeId,
                    customer_id: data.customer_id,
                    entry_date: entryDate,
                    entry_time: entryTime,
                    transaction_type: data.transaction_type,
                    reference_type: data.reference_type ?? null,
                    reference_id: data.reference_id ?? null,
                    reference_number: data.reference_number ?? null,
                    debit_amount: data.debit_amount ?? 0,
                    credit_amount: data.credit_amount ?? 0,
                    payment_method: data.payment_method ?? null,
                    payment_reference: data.payment_reference ?? null,
                    notes: data.notes ?? null,
                    processed_by: user.id,
                } as never)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: entry as unknown as CustomerLedgerEntry, error: null };
        } catch {
            return { data: null, error: "Failed to create ledger entry" };
        }
    },

    /**
     * Record a payment from a customer (reduces outstanding balance).
     * Creates a PAYMENT_RECEIVED ledger entry and updates outstanding_balance.
     */
    recordPayment: async (
        storeId: string,
        data: RecordPaymentRequest
    ): Promise<ServiceResponse<CustomerLedgerEntry>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;
            if (!user) return { data: null, error: "Not authenticated" };

            const now = new Date();
            const entryDate = now.toISOString().split("T")[0];
            const entryTime = now.toTimeString().split(" ")[0];

            // Create the payment ledger entry
            const { data: entry, error: ledgerError } = await getClient()
                .from("customer_ledger")
                .insert({
                    store_id: storeId,
                    customer_id: data.customer_id,
                    entry_date: entryDate,
                    entry_time: entryTime,
                    transaction_type: "PAYMENT_RECEIVED",
                    debit_amount: 0,
                    credit_amount: data.amount,
                    payment_method: data.payment_method,
                    payment_reference: data.payment_reference ?? null,
                    notes: data.notes ?? null,
                    processed_by: user.id,
                } as never)
                .select()
                .single();

            if (ledgerError) return { data: null, error: ledgerError.message };

            // Update customer outstanding_balance
            // Note: in production, the DB trigger (record_payment_in_ledger) handles this.
            // This explicit update is a safety net.
            const { error: balanceError } = await getClient().rpc("update_customer_balance_on_payment", {
                p_customer_id: data.customer_id,
                p_amount: data.amount,
            });

            // If RPC doesn't exist, fallback to manual update
            if (balanceError) {
                await getClient()
                    .from("customers")
                    .update({
                        outstanding_balance: getClient().rpc("greatest", { a: 0, b: undefined }),
                    } as never)
                    .eq("id", data.customer_id)
                    .eq("store_id", storeId);
            }

            return { data: entry as unknown as CustomerLedgerEntry, error: null };
        } catch {
            return { data: null, error: "Failed to record payment" };
        }
    },

    // ========================================================================
    // CREDIT NOTES
    // ========================================================================

    /**
     * Get credit notes for a customer.
     * Uses `idx_credit_notes_customer` index.
     */
    getCreditNotes: async (
        storeId: string,
        customerId: string
    ): Promise<ServiceResponse<CreditNote[]>> => {
        try {
            const { data, error } = await getClient()
                .from("credit_notes")
                .select("*")
                .eq("customer_id", customerId)
                .eq("store_id", storeId)
                .order("issued_date", { ascending: false });

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as CreditNote[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch credit notes" };
        }
    },

    /**
     * Get all active (usable) credit notes for a store.
     * Uses `idx_credit_notes_active` partial index.
     */
    getActiveCreditNotes: async (
        storeId: string,
        customerId?: string
    ): Promise<ServiceResponse<CreditNote[]>> => {
        try {
            let query = getClient()
                .from("credit_notes")
                .select("*")
                .eq("store_id", storeId)
                .eq("is_active", true)
                .eq("is_fully_redeemed", false);

            if (customerId) {
                query = query.eq("customer_id", customerId);
            }

            const { data, error } = await query.order("issued_date", { ascending: false });

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as CreditNote[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch active credit notes" };
        }
    },

    /**
     * Get a single credit note by ID.
     */
    getCreditNoteById: async (
        storeId: string,
        creditNoteId: string
    ): Promise<ServiceResponse<CreditNote>> => {
        try {
            const { data, error } = await getClient()
                .from("credit_notes")
                .select("*")
                .eq("id", creditNoteId)
                .eq("store_id", storeId)
                .single();

            if (error) return { data: null, error: error.message };
            return { data: data as unknown as CreditNote, error: null };
        } catch {
            return { data: null, error: "Failed to fetch credit note" };
        }
    },

    // ========================================================================
    // CREDIT SUMMARY (uses v_customer_credit_summary view)
    // ========================================================================

    /**
     * Get credit summary for a specific customer from the DB view.
     */
    getCreditSummary: async (
        storeId: string,
        customerId: string
    ): Promise<ServiceResponse<CustomerCreditSummary>> => {
        try {
            const { data, error } = await getClient()
                .from("v_customer_credit_summary")
                .select("*")
                .eq("customer_id", customerId)
                .eq("store_id", storeId)
                .single();

            if (error) {
                if (error.code === "PGRST116") {
                    return { data: null, error: "No credit summary found for this customer" };
                }
                return { data: null, error: error.message };
            }

            return { data: data as unknown as CustomerCreditSummary, error: null };
        } catch {
            return { data: null, error: "Failed to fetch credit summary" };
        }
    },

    /**
     * Get all customers with outstanding balances (credit summary view).
     * Uses `idx_customers_outstanding` partial index.
     */
    getCustomersWithOutstanding: async (
        storeId: string
    ): Promise<ServiceResponse<CustomerCreditSummary[]>> => {
        try {
            const { data, error } = await getClient()
                .from("v_customer_credit_summary")
                .select("*")
                .eq("store_id", storeId)
                .gt("outstanding_balance", 0)
                .order("outstanding_balance", { ascending: false });

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as CustomerCreditSummary[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch customers with outstanding balance" };
        }
    },

    // ========================================================================
    // LOYALTY POINTS
    // ========================================================================

    /**
     * Adjust loyalty points for a customer (add or deduct).
     */
    adjustLoyaltyPoints: async (
        storeId: string,
        customerId: string,
        data: AdjustLoyaltyPointsRequest
    ): Promise<ServiceResponse<Customer>> => {
        try {
            // Fetch current customer to calculate new points
            const { data: current, error: fetchError } = await getClient()
                .from("customers")
                .select("loyalty_points, total_points_earned, total_points_redeemed")
                .eq("id", customerId)
                .eq("store_id", storeId)
                .single();

            if (fetchError) return { data: null, error: fetchError.message };
            if (!current) return { data: null, error: "Customer not found" };

            const currentCustomer = current as unknown as Pick<Customer, "loyalty_points" | "total_points_earned" | "total_points_redeemed">;
            const newPoints = currentCustomer.loyalty_points + data.points;

            if (newPoints < 0) {
                return { data: null, error: "Insufficient loyalty points for this deduction" };
            }

            const updateData: Record<string, unknown> = {
                loyalty_points: newPoints,
            };

            if (data.points > 0) {
                updateData.total_points_earned = currentCustomer.total_points_earned + data.points;
            } else {
                updateData.total_points_redeemed = currentCustomer.total_points_redeemed + Math.abs(data.points);
            }

            const { data: updated, error: updateError } = await getClient()
                .from("customers")
                .update(updateData as never)
                .eq("id", customerId)
                .eq("store_id", storeId)
                .select()
                .single();

            if (updateError) return { data: null, error: updateError.message };
            return { data: updated as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to adjust loyalty points" };
        }
    },

    // ========================================================================
    // DASHBOARD & STATS
    // ========================================================================

    /**
     * Get dashboard statistics for the customer module.
     * Runs multiple lightweight queries in parallel for performance.
     */
    getDashboardStats: async (
        storeId: string
    ): Promise<ServiceResponse<CustomerDashboardStats>> => {
        try {
            const startOfMonth = new Date();
            startOfMonth.setDate(1);
            startOfMonth.setHours(0, 0, 0, 0);
            const monthStart = startOfMonth.toISOString();

            // Run all count queries in parallel
            const [
                totalRes,
                activeRes,
                blacklistedRes,
                creditRes,
                outstandingRes,
                newThisMonthRes,
                vipRes,
                corporateRes,
                topCustomersRes,
                typeDistRes,
            ] = await Promise.all([
                // Total customers
                getClient()
                    .from("customers")
                    .select("id", { count: "exact", head: true })
                    .eq("store_id", storeId),
                // Active
                getClient()
                    .from("customers")
                    .select("id", { count: "exact", head: true })
                    .eq("store_id", storeId)
                    .eq("is_active", true)
                    .eq("is_blacklisted", false),
                // Blacklisted
                getClient()
                    .from("customers")
                    .select("id", { count: "exact", head: true })
                    .eq("store_id", storeId)
                    .eq("is_blacklisted", true),
                // With credit allowed
                getClient()
                    .from("customers")
                    .select("id", { count: "exact", head: true })
                    .eq("store_id", storeId)
                    .eq("is_credit_allowed", true),
                // Outstanding balance total — sum via query
                getClient()
                    .from("customers")
                    .select("outstanding_balance, loyalty_points")
                    .eq("store_id", storeId)
                    .gt("outstanding_balance", 0),
                // New this month
                getClient()
                    .from("customers")
                    .select("id", { count: "exact", head: true })
                    .eq("store_id", storeId)
                    .gte("created_at", monthStart),
                // VIP
                getClient()
                    .from("customers")
                    .select("id", { count: "exact", head: true })
                    .eq("store_id", storeId)
                    .eq("customer_type", "VIP"),
                // Corporate
                getClient()
                    .from("customers")
                    .select("id", { count: "exact", head: true })
                    .eq("store_id", storeId)
                    .eq("customer_type", "CORPORATE"),
                // Top customers by purchases
                getClient()
                    .from("customers")
                    .select("id, name, phone, total_purchases, total_visits")
                    .eq("store_id", storeId)
                    .eq("is_active", true)
                    .order("total_purchases", { ascending: false })
                    .limit(10),
                // Customer type distribution
                getClient()
                    .from("customers")
                    .select("customer_type")
                    .eq("store_id", storeId),
            ]);

            // Calculate outstanding total and loyalty points from fetched rows
            const outstandingRows = (outstandingRes.data ?? []) as unknown as Array<{
                outstanding_balance: number;
                loyalty_points: number;
            }>;
            const totalOutstanding = outstandingRows.reduce((sum, r) => sum + r.outstanding_balance, 0);

            // Calculate total loyalty points from all customers
            const allCustomersForPoints = (typeDistRes.data ?? []) as unknown as Array<{ customer_type: string }>;
            // We need a separate query for loyalty points sum — reuse outstanding rows
            // Actually, let's calculate loyalty from the type distribution query
            // We can't get loyalty_points from the type distribution query, so use outstanding rows
            // For a proper total, we'd need another query or include loyalty_points in typeDistRes
            // Let's just use outstanding data which is a subset — for accurate totals, get from all customers
            let totalLoyaltyPoints = 0;
            // Fetch all loyalty points
            const loyaltyRes = await getClient()
                .from("customers")
                .select("loyalty_points")
                .eq("store_id", storeId);
            if (loyaltyRes.data) {
                totalLoyaltyPoints = (loyaltyRes.data as unknown as Array<{ loyalty_points: number }>)
                    .reduce((sum, r) => sum + r.loyalty_points, 0);
            }

            const totalCount = totalRes.count ?? 0;
            const activeCount = activeRes.count ?? 0;
            const inactiveCount = totalCount - activeCount - (blacklistedRes.count ?? 0);

            // Build type distribution
            const typeCountMap = new Map<CustomerType, number>();
            for (const row of allCustomersForPoints) {
                const ct = row.customer_type as CustomerType;
                typeCountMap.set(ct, (typeCountMap.get(ct) ?? 0) + 1);
            }
            const customersByType: CustomerDashboardStats["customers_by_type"] = [];
            for (const [customer_type, count] of typeCountMap) {
                customersByType.push({ customer_type, count });
            }
            customersByType.sort((a, b) => b.count - a.count);

            const topCustomers = ((topCustomersRes.data ?? []) as unknown as Array<{
                id: string;
                name: string;
                phone: string;
                total_purchases: number;
                total_visits: number;
            }>).map((c) => ({
                id: c.id,
                name: c.name,
                phone: c.phone,
                total_purchases: c.total_purchases,
                total_visits: c.total_visits,
            }));

            return {
                data: {
                    total_customers: totalCount,
                    active_customers: activeCount,
                    inactive_customers: inactiveCount,
                    blacklisted_customers: blacklistedRes.count ?? 0,
                    customers_with_credit: creditRes.count ?? 0,
                    total_outstanding: totalOutstanding,
                    total_loyalty_points: totalLoyaltyPoints,
                    new_customers_this_month: newThisMonthRes.count ?? 0,
                    vip_customers: vipRes.count ?? 0,
                    corporate_customers: corporateRes.count ?? 0,
                    top_customers: topCustomers,
                    customers_by_type: customersByType,
                },
                error: null,
            };
        } catch {
            return { data: null, error: "Failed to fetch dashboard statistics" };
        }
    },

    // ========================================================================
    // TAGS MANAGEMENT
    // ========================================================================

    /**
     * Add tags to a customer (merges with existing tags, no duplicates).
     */
    addTags: async (
        storeId: string,
        customerId: string,
        newTags: string[]
    ): Promise<ServiceResponse<Customer>> => {
        try {
            // Fetch current tags
            const { data: current, error: fetchError } = await getClient()
                .from("customers")
                .select("tags")
                .eq("id", customerId)
                .eq("store_id", storeId)
                .single();

            if (fetchError) return { data: null, error: fetchError.message };

            const currentTags: string[] = (current as unknown as { tags: string[] | null }).tags ?? [];
            const mergedTags = Array.from(new Set([...currentTags, ...newTags]));

            const { data: updated, error } = await getClient()
                .from("customers")
                .update({ tags: mergedTags } as never)
                .eq("id", customerId)
                .eq("store_id", storeId)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: updated as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to add tags" };
        }
    },

    /**
     * Remove tags from a customer.
     */
    removeTags: async (
        storeId: string,
        customerId: string,
        tagsToRemove: string[]
    ): Promise<ServiceResponse<Customer>> => {
        try {
            const { data: current, error: fetchError } = await getClient()
                .from("customers")
                .select("tags")
                .eq("id", customerId)
                .eq("store_id", storeId)
                .single();

            if (fetchError) return { data: null, error: fetchError.message };

            const currentTags: string[] = (current as unknown as { tags: string[] | null }).tags ?? [];
            const removeSet = new Set(tagsToRemove);
            const filteredTags = currentTags.filter((t) => !removeSet.has(t));

            const { data: updated, error } = await getClient()
                .from("customers")
                .update({ tags: filteredTags } as never)
                .eq("id", customerId)
                .eq("store_id", storeId)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: updated as unknown as Customer, error: null };
        } catch {
            return { data: null, error: "Failed to remove tags" };
        }
    },

    // ========================================================================
    // BULK OPERATIONS
    // ========================================================================

    /**
     * Bulk update customer type for multiple customers.
     */
    bulkUpdateType: async (
        storeId: string,
        customerIds: string[],
        customerType: CustomerType
    ): Promise<ServiceResponse<number>> => {
        try {
            const { error, count } = await getClient()
                .from("customers")
                .update({ customer_type: customerType } as never)
                .eq("store_id", storeId)
                .in("id", customerIds);

            if (error) return { data: null, error: error.message };
            return { data: count ?? customerIds.length, error: null };
        } catch {
            return { data: null, error: "Failed to bulk update customer type" };
        }
    },

    /**
     * Bulk deactivate customers.
     */
    bulkDeactivate: async (
        storeId: string,
        customerIds: string[]
    ): Promise<ServiceResponse<number>> => {
        try {
            const { error, count } = await getClient()
                .from("customers")
                .update({ is_active: false } as never)
                .eq("store_id", storeId)
                .in("id", customerIds);

            if (error) return { data: null, error: error.message };
            return { data: count ?? customerIds.length, error: null };
        } catch {
            return { data: null, error: "Failed to bulk deactivate customers" };
        }
    },

    /**
     * Bulk add tags to multiple customers.
     */
    bulkAddTags: async (
        storeId: string,
        customerIds: string[],
        tags: string[]
    ): Promise<ServiceResponse<number>> => {
        try {
            let successCount = 0;

            for (const id of customerIds) {
                const result = await customerService.addTags(storeId, id, tags);
                if (!result.error) successCount++;
            }

            return { data: successCount, error: null };
        } catch {
            return { data: null, error: "Failed to bulk add tags" };
        }
    },
};
