import { createClient } from "@/lib/supabase/client";
import type { ServiceResponse } from "@/types/api.types";
import type {
    PurchaseOrder,
    PurchaseOrderItem,
    PurchasePayment,
    PurchaseReturn,
    PurchaseReturnItem,
    EnrichedPurchaseOrder,
    CreatePurchaseOrderRequest,
    UpdatePurchaseOrderRequest,
    CreatePurchaseOrderItemRequest,
    UpdatePurchaseOrderItemRequest,
    ReceiveItemRequest,
    CreatePurchasePaymentRequest,
    CreatePurchaseReturnRequest,
    PurchaseOrderFilters,
    PurchaseOrderPagination,
    PurchaseOrderListResponse,
    PurchaseDashboardStats,
    SupplierPurchaseSummary,
    CancelPurchaseOrderRequest,
} from "@/types/purchase.types";
import { buildItemPayload } from "@/utils/purchase.utils";

const getClient = () => createClient();

// ============================================================================
// PURCHASE SERVICE
// All CRUD operations for purchase orders, items, payments, and returns
// ============================================================================

export const purchaseService = {
    // ========================================================================
    // PURCHASE ORDER CRUD
    // ========================================================================

    /**
     * Create a new purchase order with items
     */
    create: async (
        storeId: string,
        data: CreatePurchaseOrderRequest
    ): Promise<ServiceResponse<PurchaseOrder>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;
            if (!user) return { data: null, error: "Not authenticated" };

            const { items, ...headerData } = data;
            const isInterState = headerData.is_inter_state ?? false;

            // Create PO header (po_number auto-generated by trigger)
            const { data: po, error: poError } = await getClient()
                .from("purchase_orders")
                .insert({
                    ...headerData,
                    store_id: storeId,
                    status: "draft",
                    payment_status: "unpaid",
                    created_by: user.id,
                    updated_by: user.id,
                } as never)
                .select()
                .single();

            if (poError) return { data: null, error: poError.message };
            if (!po) return { data: null, error: "Failed to create purchase order" };

            const poRecord = po as unknown as PurchaseOrder;

            // Create PO items with calculated tax fields
            const itemPayloads = items.map((item) => ({
                ...buildItemPayload(item, isInterState),
                purchase_order_id: poRecord.id,
                store_id: storeId,
            }));

            const { error: itemsError } = await getClient()
                .from("purchase_order_items")
                .insert(itemPayloads as never[]);

            if (itemsError) {
                // Clean up the created PO header on item insertion failure
                await getClient()
                    .from("purchase_orders")
                    .delete()
                    .eq("id", poRecord.id);
                return { data: null, error: `Failed to create items: ${itemsError.message}` };
            }

            // Re-fetch the PO (trigger recalculates totals)
            const { data: refreshed, error: refetchError } = await getClient()
                .from("purchase_orders")
                .select("*")
                .eq("id", poRecord.id)
                .single();

            if (refetchError) return { data: poRecord, error: null };
            return { data: refreshed as unknown as PurchaseOrder, error: null };
        } catch {
            return { data: null, error: "Failed to create purchase order" };
        }
    },

    /**
     * Get a purchase order by ID with items, payments, returns
     */
    getById: async (
        storeId: string,
        poId: string
    ): Promise<ServiceResponse<EnrichedPurchaseOrder>> => {
        try {
            const { data: po, error } = await getClient()
                .from("purchase_orders")
                .select(`
                    *,
                    purchase_order_items (*),
                    purchase_payments (*),
                    purchase_returns (
                        *,
                        purchase_return_items (*)
                    ),
                    suppliers:supplier_id (
                        id, name, supplier_code, gstin, phone, email
                    )
                `)
                .eq("id", poId)
                .eq("store_id", storeId)
                .single();

            if (error) return { data: null, error: error.message };
            if (!po) return { data: null, error: "Purchase order not found" };

            const enriched: EnrichedPurchaseOrder = {
                ...(po as unknown as PurchaseOrder),
                items: (po.purchase_order_items ?? []) as unknown as PurchaseOrderItem[],
                payments: (po.purchase_payments ?? []) as unknown as PurchasePayment[],
                returns: (po.purchase_returns ?? []) as unknown as PurchaseReturn[],
                supplier: po.suppliers as unknown as EnrichedPurchaseOrder["supplier"],
            };

            return { data: enriched, error: null };
        } catch {
            return { data: null, error: "Failed to fetch purchase order" };
        }
    },

    /**
     * Get paginated list of purchase orders with filters
     */
    getList: async (
        storeId: string,
        filters?: PurchaseOrderFilters,
        pagination?: PurchaseOrderPagination
    ): Promise<ServiceResponse<PurchaseOrderListResponse>> => {
        try {
            const page = pagination?.page ?? 1;
            const limit = pagination?.limit ?? 10;
            const sortBy = pagination?.sort_by ?? "created_at";
            const sortOrder = pagination?.sort_order ?? "desc";
            const offset = (page - 1) * limit;

            let query = getClient()
                .from("purchase_orders")
                .select("*", { count: "exact" })
                .eq("store_id", storeId);

            // Apply filters
            if (filters) {
                if (filters.status) {
                    query = query.eq("status", filters.status);
                }
                if (filters.payment_status) {
                    query = query.eq("payment_status", filters.payment_status);
                }
                if (filters.supplier_id) {
                    query = query.eq("supplier_id", filters.supplier_id);
                }
                if (filters.date_from) {
                    query = query.gte("order_date", filters.date_from);
                }
                if (filters.date_to) {
                    query = query.lte("order_date", filters.date_to);
                }
                if (filters.is_inter_state !== undefined) {
                    query = query.eq("is_inter_state", filters.is_inter_state);
                }
                if (filters.min_amount != null) {
                    query = query.gte("grand_total", filters.min_amount);
                }
                if (filters.max_amount != null) {
                    query = query.lte("grand_total", filters.max_amount);
                }
                if (filters.has_invoice === true) {
                    query = query.not("invoice_number", "is", null);
                } else if (filters.has_invoice === false) {
                    query = query.is("invoice_number", null);
                }
                if (filters.tags && filters.tags.length > 0) {
                    query = query.overlaps("tags", filters.tags);
                }
                if (filters.search) {
                    query = query.or(
                        `po_number.ilike.%${filters.search}%,` +
                        `invoice_number.ilike.%${filters.search}%,` +
                        `supplier_name.ilike.%${filters.search}%,` +
                        `reference_number.ilike.%${filters.search}%`
                    );
                }
            }

            // Apply sorting and pagination
            query = query
                .order(sortBy, { ascending: sortOrder === "asc" })
                .range(offset, offset + limit - 1);

            const { data, error, count } = await query;

            if (error) return { data: null, error: error.message };

            const total = count ?? 0;
            const totalPages = Math.ceil(total / limit);

            return {
                data: {
                    orders: (data ?? []) as unknown as PurchaseOrder[],
                    total,
                    page,
                    limit,
                    total_pages: totalPages,
                },
                error: null,
            };
        } catch {
            return { data: null, error: "Failed to fetch purchase orders" };
        }
    },

    /**
     * Update a purchase order header (only draft orders)
     */
    update: async (
        storeId: string,
        poId: string,
        data: UpdatePurchaseOrderRequest
    ): Promise<ServiceResponse<PurchaseOrder>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;

            // Separate items from the PO header fields — items go to a different table
            const { items, ...headerData } = data;
            const isInterState = headerData.is_inter_state ?? false;

            // Update the PO header
            const { error: headerError } = await getClient()
                .from("purchase_orders")
                .update({
                    ...headerData,
                    updated_at: new Date().toISOString(),
                    updated_by: user?.id,
                } as never)
                .eq("id", poId)
                .eq("store_id", storeId)
                .eq("status", "draft");

            if (headerError) return { data: null, error: headerError.message };

            // If items were provided, replace all existing items
            if (items && items.length > 0) {
                // Delete existing items
                const { error: deleteError } = await getClient()
                    .from("purchase_order_items")
                    .delete()
                    .eq("purchase_order_id", poId);

                if (deleteError) return { data: null, error: `Failed to clear old items: ${deleteError.message}` };

                // Insert new items
                const itemPayloads = items.map((item) => ({
                    ...buildItemPayload(item, isInterState),
                    purchase_order_id: poId,
                    store_id: storeId,
                }));

                const { error: insertError } = await getClient()
                    .from("purchase_order_items")
                    .insert(itemPayloads as never[]);

                if (insertError) return { data: null, error: `Failed to update items: ${insertError.message}` };
            }

            // Re-fetch the updated PO (triggers recalculate totals)
            const { data: refreshed, error: refetchError } = await getClient()
                .from("purchase_orders")
                .select("*")
                .eq("id", poId)
                .single();

            if (refetchError) return { data: null, error: refetchError.message };
            return { data: refreshed as unknown as PurchaseOrder, error: null };
        } catch {
            return { data: null, error: "Failed to update purchase order" };
        }
    },

    /**
     * Delete a purchase order (only draft)
     */
    delete: async (
        storeId: string,
        poId: string
    ): Promise<ServiceResponse<null>> => {
        try {
            const { error } = await getClient()
                .from("purchase_orders")
                .delete()
                .eq("id", poId)
                .eq("store_id", storeId);

            if (error) return { data: null, error: error.message };
            return { data: null, error: null };
        } catch {
            return { data: null, error: "Failed to delete purchase order" };
        }
    },

    // ========================================================================
    // STATUS TRANSITIONS
    // ========================================================================

    /**
     * Confirm a draft purchase order
     */
    confirm: async (
        storeId: string,
        poId: string
    ): Promise<ServiceResponse<PurchaseOrder>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;

            const { data: po, error } = await getClient()
                .from("purchase_orders")
                .update({
                    status: "confirmed",
                    approved_by: user?.id,
                    approved_at: new Date().toISOString(),
                    updated_at: new Date().toISOString(),
                    updated_by: user?.id,
                } as never)
                .eq("id", poId)
                .eq("store_id", storeId)
                .eq("status", "draft")
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: po as unknown as PurchaseOrder, error: null };
        } catch {
            return { data: null, error: "Failed to confirm purchase order" };
        }
    },

    /**
     * Cancel a purchase order (draft or confirmed only)
     */
    cancel: async (
        storeId: string,
        poId: string,
        request: CancelPurchaseOrderRequest
    ): Promise<ServiceResponse<PurchaseOrder>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;

            const { data: po, error } = await getClient()
                .from("purchase_orders")
                .update({
                    status: "cancelled",
                    cancelled_by: user?.id,
                    cancelled_at: new Date().toISOString(),
                    cancellation_reason: request.cancellation_reason,
                    updated_at: new Date().toISOString(),
                    updated_by: user?.id,
                } as never)
                .eq("id", poId)
                .eq("store_id", storeId)
                .in("status", ["draft", "confirmed"])
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: po as unknown as PurchaseOrder, error: null };
        } catch {
            return { data: null, error: "Failed to cancel purchase order" };
        }
    },

    // ========================================================================
    // PURCHASE ORDER ITEMS
    // ========================================================================

    /**
     * Get items for a purchase order
     */
    getItems: async (poId: string): Promise<ServiceResponse<PurchaseOrderItem[]>> => {
        try {
            const { data, error } = await getClient()
                .from("purchase_order_items")
                .select("*")
                .eq("purchase_order_id", poId)
                .order("created_at", { ascending: true });

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as PurchaseOrderItem[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch purchase order items" };
        }
    },

    /**
     * Add an item to a draft purchase order
     */
    addItem: async (
        storeId: string,
        poId: string,
        item: CreatePurchaseOrderItemRequest,
        isInterState: boolean
    ): Promise<ServiceResponse<PurchaseOrderItem>> => {
        try {
            const payload = buildItemPayload(item, isInterState);

            const { data, error } = await getClient()
                .from("purchase_order_items")
                .insert({
                    ...payload,
                    purchase_order_id: poId,
                    store_id: storeId,
                } as never)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: data as unknown as PurchaseOrderItem, error: null };
        } catch {
            return { data: null, error: "Failed to add item" };
        }
    },

    /**
     * Update an item in a draft purchase order
     */
    updateItem: async (
        storeId: string,
        itemId: string,
        data: UpdatePurchaseOrderItemRequest
    ): Promise<ServiceResponse<PurchaseOrderItem>> => {
        try {
            const { data: item, error } = await getClient()
                .from("purchase_order_items")
                .update({
                    ...data,
                    updated_at: new Date().toISOString(),
                } as never)
                .eq("id", itemId)
                .eq("store_id", storeId)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: item as unknown as PurchaseOrderItem, error: null };
        } catch {
            return { data: null, error: "Failed to update item" };
        }
    },

    /**
     * Remove an item from a draft purchase order
     */
    removeItem: async (
        storeId: string,
        itemId: string
    ): Promise<ServiceResponse<null>> => {
        try {
            const { error } = await getClient()
                .from("purchase_order_items")
                .delete()
                .eq("id", itemId)
                .eq("store_id", storeId);

            if (error) return { data: null, error: error.message };
            return { data: null, error: null };
        } catch {
            return { data: null, error: "Failed to remove item" };
        }
    },

    /**
     * Receive items (update received_quantity)
     */
    receiveItems: async (
        storeId: string,
        poId: string,
        items: ReceiveItemRequest[]
    ): Promise<ServiceResponse<PurchaseOrderItem[]>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;

            // Update PO updated_by for the receiving trigger
            await getClient()
                .from("purchase_orders")
                .update({
                    updated_by: user?.id,
                    updated_at: new Date().toISOString(),
                } as never)
                .eq("id", poId)
                .eq("store_id", storeId);

            const results: PurchaseOrderItem[] = [];

            for (const item of items) {
                const updateData: Record<string, unknown> = {
                    received_quantity: item.received_quantity,
                    updated_at: new Date().toISOString(),
                };

                if (item.batch_number) updateData.batch_number = item.batch_number;
                if (item.manufacturing_date) updateData.manufacturing_date = item.manufacturing_date;
                if (item.expiry_date) updateData.expiry_date = item.expiry_date;

                const { data, error } = await getClient()
                    .from("purchase_order_items")
                    .update(updateData as never)
                    .eq("id", item.item_id)
                    .eq("store_id", storeId)
                    .select()
                    .single();

                if (error) {
                    return { data: null, error: `Failed to receive item: ${error.message}` };
                }

                if (data) results.push(data as unknown as PurchaseOrderItem);
            }

            return { data: results, error: null };
        } catch {
            return { data: null, error: "Failed to receive items" };
        }
    },

    // ========================================================================
    // PURCHASE PAYMENTS
    // ========================================================================

    /**
     * Get payments for a purchase order
     */
    getPayments: async (poId: string): Promise<ServiceResponse<PurchasePayment[]>> => {
        try {
            const { data, error } = await getClient()
                .from("purchase_payments")
                .select("*")
                .eq("purchase_order_id", poId)
                .order("payment_date", { ascending: false });

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as PurchasePayment[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch payments" };
        }
    },

    /**
     * Add a payment to a purchase order
     */
    addPayment: async (
        storeId: string,
        poId: string,
        data: CreatePurchasePaymentRequest
    ): Promise<ServiceResponse<PurchasePayment>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;
            if (!user) return { data: null, error: "Not authenticated" };

            const { data: payment, error } = await getClient()
                .from("purchase_payments")
                .insert({
                    ...data,
                    purchase_order_id: poId,
                    store_id: storeId,
                    status: "completed",
                    created_by: user.id,
                } as never)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: payment as unknown as PurchasePayment, error: null };
        } catch {
            return { data: null, error: "Failed to add payment" };
        }
    },

    /**
     * Cancel a payment
     */
    cancelPayment: async (
        storeId: string,
        paymentId: string
    ): Promise<ServiceResponse<PurchasePayment>> => {
        try {
            const { data: payment, error } = await getClient()
                .from("purchase_payments")
                .update({
                    status: "cancelled",
                    updated_at: new Date().toISOString(),
                } as never)
                .eq("id", paymentId)
                .eq("store_id", storeId)
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: payment as unknown as PurchasePayment, error: null };
        } catch {
            return { data: null, error: "Failed to cancel payment" };
        }
    },

    // ========================================================================
    // PURCHASE RETURNS
    // ========================================================================

    /**
     * Get returns for a purchase order
     */
    getReturns: async (poId: string): Promise<ServiceResponse<PurchaseReturn[]>> => {
        try {
            const { data, error } = await getClient()
                .from("purchase_returns")
                .select(`
                    *,
                    purchase_return_items (*)
                `)
                .eq("purchase_order_id", poId)
                .order("return_date", { ascending: false });

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as PurchaseReturn[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch returns" };
        }
    },

    /**
     * Create a purchase return with items
     */
    createReturn: async (
        storeId: string,
        data: CreatePurchaseReturnRequest
    ): Promise<ServiceResponse<PurchaseReturn>> => {
        try {
            const user = (await getClient().auth.getUser()).data.user;
            if (!user) return { data: null, error: "Not authenticated" };

            const { items, ...headerData } = data;

            // Fetch the PO to determine inter-state
            const { data: po } = await getClient()
                .from("purchase_orders")
                .select("is_inter_state")
                .eq("id", data.purchase_order_id)
                .single();

            const isInterState = (po as Record<string, unknown> | null)?.is_inter_state as boolean ?? false;

            // Calculate return item totals
            const returnItems = items.map((item) => {
                const lineTotal = item.return_quantity * item.unit_price;
                const gstAmount = (lineTotal * item.gst_percentage) / 100;
                const cessAmount = (lineTotal * (item.cess_percentage ?? 0)) / 100;

                let cgstAmt = 0;
                let sgstAmt = 0;
                let igstAmt = 0;

                if (isInterState) {
                    igstAmt = gstAmount;
                } else {
                    cgstAmt = gstAmount / 2;
                    sgstAmt = gstAmount / 2;
                }

                const taxAmount = cgstAmt + sgstAmt + igstAmt + cessAmount;

                return {
                    ...item,
                    store_id: storeId,
                    line_total: lineTotal,
                    cgst_amount: Math.round(cgstAmt * 100) / 100,
                    sgst_amount: Math.round(sgstAmt * 100) / 100,
                    igst_amount: Math.round(igstAmt * 100) / 100,
                    cess_amount: Math.round(cessAmount * 100) / 100,
                    tax_amount: Math.round(taxAmount * 100) / 100,
                    total_amount: Math.round((lineTotal + taxAmount) * 100) / 100,
                };
            });

            // Calculate header totals
            const subtotal = returnItems.reduce((sum, i) => sum + i.line_total, 0);
            const totalCgst = returnItems.reduce((sum, i) => sum + i.cgst_amount, 0);
            const totalSgst = returnItems.reduce((sum, i) => sum + i.sgst_amount, 0);
            const totalIgst = returnItems.reduce((sum, i) => sum + i.igst_amount, 0);
            const totalCess = returnItems.reduce((sum, i) => sum + i.cess_amount, 0);
            const totalTax = totalCgst + totalSgst + totalIgst + totalCess;
            const grandTotal = subtotal + totalTax;

            // Create return header
            const { data: returnRecord, error: returnError } = await getClient()
                .from("purchase_returns")
                .insert({
                    ...headerData,
                    store_id: storeId,
                    status: "draft",
                    subtotal: Math.round(subtotal * 100) / 100,
                    cgst_amount: Math.round(totalCgst * 100) / 100,
                    sgst_amount: Math.round(totalSgst * 100) / 100,
                    igst_amount: Math.round(totalIgst * 100) / 100,
                    cess_amount: Math.round(totalCess * 100) / 100,
                    total_tax: Math.round(totalTax * 100) / 100,
                    grand_total: Math.round(grandTotal * 100) / 100,
                    created_by: user.id,
                } as never)
                .select()
                .single();

            if (returnError) return { data: null, error: returnError.message };
            if (!returnRecord) return { data: null, error: "Failed to create return" };

            const retRecord = returnRecord as unknown as PurchaseReturn;

            // Create return items
            const returnItemPayloads = returnItems.map((item) => ({
                ...item,
                purchase_return_id: retRecord.id,
            }));

            const { error: itemsError } = await getClient()
                .from("purchase_return_items")
                .insert(returnItemPayloads as never[]);

            if (itemsError) {
                await getClient()
                    .from("purchase_returns")
                    .delete()
                    .eq("id", retRecord.id);
                return { data: null, error: `Failed to create return items: ${itemsError.message}` };
            }

            return { data: retRecord, error: null };
        } catch {
            return { data: null, error: "Failed to create purchase return" };
        }
    },

    /**
     * Complete a purchase return (triggers inventory update)
     */
    completeReturn: async (
        storeId: string,
        returnId: string
    ): Promise<ServiceResponse<PurchaseReturn>> => {
        try {
            const { data, error } = await getClient()
                .from("purchase_returns")
                .update({
                    status: "completed",
                    updated_at: new Date().toISOString(),
                } as never)
                .eq("id", returnId)
                .eq("store_id", storeId)
                .in("status", ["draft", "confirmed"])
                .select()
                .single();

            if (error) return { data: null, error: error.message };
            return { data: data as unknown as PurchaseReturn, error: null };
        } catch {
            return { data: null, error: "Failed to complete return" };
        }
    },

    // ========================================================================
    // STATISTICS / DASHBOARD
    // ========================================================================

    /**
     * Get purchase dashboard stats via RPC
     */
    getDashboardStats: async (
        storeId: string
    ): Promise<ServiceResponse<PurchaseDashboardStats>> => {
        try {
            const { data, error } = await getClient().rpc("get_purchase_dashboard_stats", {
                p_store_id: storeId,
            });

            if (error) return { data: null, error: error.message };
            return { data: data as unknown as PurchaseDashboardStats, error: null };
        } catch {
            return { data: null, error: "Failed to fetch dashboard stats" };
        }
    },

    /**
     * Get supplier purchase summary via RPC
     */
    getSupplierPurchaseSummary: async (
        storeId: string,
        supplierId: string
    ): Promise<ServiceResponse<SupplierPurchaseSummary>> => {
        try {
            const { data, error } = await getClient().rpc("get_supplier_purchase_summary", {
                p_store_id: storeId,
                p_supplier_id: supplierId,
            });

            if (error) return { data: null, error: error.message };
            return { data: data as unknown as SupplierPurchaseSummary, error: null };
        } catch {
            return { data: null, error: "Failed to fetch supplier purchase summary" };
        }
    },

    // ========================================================================
    // UTILITY QUERIES
    // ========================================================================

    /**
     * Check if PO number is unique (usually auto-generated but for validation)
     */
    isPONumberUnique: async (
        storeId: string,
        poNumber: string,
        excludeId?: string
    ): Promise<ServiceResponse<boolean>> => {
        try {
            let query = getClient()
                .from("purchase_orders")
                .select("id", { count: "exact", head: true })
                .eq("store_id", storeId)
                .eq("po_number", poNumber);

            if (excludeId) {
                query = query.neq("id", excludeId);
            }

            const { count, error } = await query;
            if (error) return { data: null, error: error.message };
            return { data: (count ?? 0) === 0, error: null };
        } catch {
            return { data: null, error: "Failed to check PO number uniqueness" };
        }
    },

    /**
     * Get recent purchase orders for quick access
     */
    getRecent: async (
        storeId: string,
        limit = 5
    ): Promise<ServiceResponse<PurchaseOrder[]>> => {
        try {
            const { data, error } = await getClient()
                .from("purchase_orders")
                .select("*")
                .eq("store_id", storeId)
                .order("created_at", { ascending: false })
                .limit(limit);

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as PurchaseOrder[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch recent orders" };
        }
    },

    /**
     * Get overdue purchase orders (unpaid past due date)
     */
    getOverdue: async (
        storeId: string
    ): Promise<ServiceResponse<PurchaseOrder[]>> => {
        try {
            const today = new Date().toISOString().split("T")[0];

            const { data, error } = await getClient()
                .from("purchase_orders")
                .select("*")
                .eq("store_id", storeId)
                .in("payment_status", ["unpaid", "partially_paid"])
                .lt("payment_due_date", today)
                .neq("status", "cancelled")
                .order("payment_due_date", { ascending: true });

            if (error) return { data: null, error: error.message };
            return { data: (data ?? []) as unknown as PurchaseOrder[], error: null };
        } catch {
            return { data: null, error: "Failed to fetch overdue orders" };
        }
    },
};
