// ============================================================================
// Database Types - Generated from Supabase Schema
// ============================================================================

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          alternate_phone: string | null;
          date_of_birth: string | null;
          gender: GenderType | null;
          profile_picture: string | null;
          notification_preferences: Json | null;
          timezone: string;
          language: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          date_of_birth?: string | null;
          gender?: GenderType | null;
          profile_picture?: string | null;
          notification_preferences?: Json | null;
          timezone?: string;
          language?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          date_of_birth?: string | null;
          gender?: GenderType | null;
          profile_picture?: string | null;
          notification_preferences?: Json | null;
          timezone?: string;
          language?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          legal_name: string | null;
          registration_type: RegistrationType | null;
          pan_number: string | null;
          tan_number: string | null;
          gstin: string | null;
          cin_number: string | null;
          msme_number: string | null;
          iec_code: string | null;
          address_line1: string | null;
          address_line2: string | null;
          landmark: string | null;
          city: string | null;
          state: string | null;
          pincode: string | null;
          country: string;
          phone: string | null;
          alternate_phone: string | null;
          email: string | null;
          website: string | null;
          logo_url: string | null;
          brand_color: string;
          bank_name: string | null;
          bank_account_number: string | null;
          ifsc_code: string | null;
          bank_branch: string | null;
          subscription_plan: string;
          subscription_status: string;
          subscription_start_date: string;
          subscription_end_date: string | null;
          billing_email: string | null;
          settings: Json;
          metadata: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          legal_name?: string | null;
          registration_type?: RegistrationType | null;
          pan_number?: string | null;
          tan_number?: string | null;
          gstin?: string | null;
          cin_number?: string | null;
          msme_number?: string | null;
          iec_code?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          landmark?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          country?: string;
          phone?: string | null;
          alternate_phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          brand_color?: string;
          bank_name?: string | null;
          bank_account_number?: string | null;
          ifsc_code?: string | null;
          bank_branch?: string | null;
          subscription_plan?: string;
          subscription_status?: string;
          subscription_start_date?: string;
          subscription_end_date?: string | null;
          billing_email?: string | null;
          settings?: Json;
          metadata?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          name?: string;
          legal_name?: string | null;
          registration_type?: RegistrationType | null;
          pan_number?: string | null;
          tan_number?: string | null;
          gstin?: string | null;
          cin_number?: string | null;
          msme_number?: string | null;
          iec_code?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          landmark?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          bank_name?: string | null;
          bank_account_number?: string | null;
          ifsc_code?: string | null;
          bank_branch?: string | null;
          settings?: Json;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      stores: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          store_code: string;
          store_type: StoreType;
          display_name: string | null;
          gstin: string | null;
          state_code: string | null;
          jurisdiction: string | null;
          jurisdiction_code: string | null;
          license_number: string | null;
          fssai_license: string | null;
          drug_license: string | null;
          pollution_certificate: string | null;
          fire_safety_certificate: string | null;
          address_line1: string;
          address_line2: string | null;
          landmark: string | null;
          city: string;
          state: string;
          pincode: string;
          country: string;
          latitude: number | null;
          longitude: number | null;
          phone: string | null;
          alternate_phone: string | null;
          email: string | null;
          contact_person: string | null;
          whatsapp_number: string | null;
          opening_date: string | null;
          closing_date: string | null;
          status: StoreStatus;
          rejection_reason: string | null;
          floor_area: number | null;
          seating_capacity: number | null;
          parking_spaces: number | null;
          has_pos_system: boolean;
          has_online_ordering: boolean;
          has_delivery: boolean;
          has_dine_in: boolean;
          has_takeaway: boolean;
          encryption_salt: string;
          ip_restriction_enabled: boolean;
          two_factor_required: boolean;
          settings: Json;
          metadata: Json;
          created_at: string;
          updated_at: string;
          approved_at: string | null;
          approved_by: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          store_code: string;
          store_type?: StoreType;
          display_name?: string | null;
          gstin?: string | null;
          state_code?: string | null;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          pincode: string;
          country?: string;
          phone?: string | null;
          email?: string | null;
          contact_person?: string | null;
          status?: StoreStatus;
          settings?: Json;
          metadata?: Json;
          created_by?: string | null;
        };
        Update: {
          name?: string;
          store_type?: StoreType;
          display_name?: string | null;
          gstin?: string | null;
          state_code?: string | null;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          pincode?: string;
          phone?: string | null;
          email?: string | null;
          status?: StoreStatus;
          settings?: Json;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          name: RoleName;
          display_name: string;
          description: string | null;
          permissions: Json;
          priority: number;
          is_system_role: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: RoleName;
          display_name: string;
          description?: string | null;
          permissions?: Json;
          priority?: number;
          is_system_role?: boolean;
        };
        Update: {
          display_name?: string;
          description?: string | null;
          permissions?: Json;
          priority?: number;
        };
        Relationships: [];
      };
      store_users: {
        Row: {
          id: string;
          store_id: string;
          user_id: string;
          role_id: string;
          employee_id: string | null;
          designation: string | null;
          department: string | null;
          reporting_manager_id: string | null;
          is_active: boolean;
          is_banned: boolean;
          banned_at: string | null;
          banned_reason: string | null;
          banned_by: string | null;
          last_login_at: string | null;
          last_login_ip: string | null;
          login_attempts: number;
          locked_until: string | null;
          two_factor_enabled: boolean;
          two_factor_secret: string | null;
          backup_codes: string[] | null;
          custom_permissions: Json | null;
          work_schedule: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          user_id: string;
          role_id: string;
          employee_id?: string | null;
          designation?: string | null;
          department?: string | null;
          is_active?: boolean;
          is_banned?: boolean;
          custom_permissions?: Json | null;
          created_by?: string | null;
        };
        Update: {
          role_id?: string;
          designation?: string | null;
          department?: string | null;
          is_active?: boolean;
          is_banned?: boolean;
          last_login_at?: string | null;
          last_login_ip?: string | null;
          login_attempts?: number;
          locked_until?: string | null;
          custom_permissions?: Json | null;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          store_id: string | null;
          organization_id: string | null;
          user_id: string | null;
          action: string;
          action_type: string | null;
          entity_type: string | null;
          entity_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          changes: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          location: string | null;
          device_info: Json | null;
          status: string;
          error_message: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          store_id?: string | null;
          organization_id?: string | null;
          user_id?: string | null;
          action: string;
          action_type?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          changes?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          status?: string;
          error_message?: string | null;
          metadata?: Json;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      sessions: {
        Row: {
          id: string;
          user_id: string;
          store_id: string | null;
          session_token: string;
          refresh_token: string | null;
          ip_address: string | null;
          user_agent: string | null;
          device_info: Json;
          location_info: Json;
          is_active: boolean;
          expires_at: string;
          last_activity: string;
          login_method: string;
          two_factor_verified: boolean;
          created_at: string;
          terminated_at: string | null;
          termination_reason: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          store_id?: string | null;
          session_token: string;
          refresh_token?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_info?: Json;
          location_info?: Json;
          is_active?: boolean;
          expires_at: string;
          last_activity?: string;
          login_method?: string;
        };
        Update: {
          is_active?: boolean;
          last_activity?: string;
          terminated_at?: string | null;
          termination_reason?: string | null;
        };
        Relationships: [];
      };
      store_settings: {
        Row: {
          id: string;
          store_id: string;
          tax_settings: Json;
          payment_gateway: Json;
          invoice_settings: Json;
          printer_settings: Json;
          business_hours: Json;
          holidays: Json;
          currency_code: string;
          currency_symbol: string;
          currency_position: string;
          thousand_separator: string;
          decimal_separator: string;
          decimal_places: number;
          gst_calculation_method: GstCalculationMethod;
          discount_settings: Json;
          inventory_settings: Json;
          sales_settings: Json;
          pos_settings: Json;
          notification_settings: Json;
          backup_settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          store_id: string;
        };
        Update: {
          tax_settings?: Json;
          payment_gateway?: Json;
          invoice_settings?: Json;
          business_hours?: Json;
          currency_code?: string;
          currency_symbol?: string;
          gst_calculation_method?: GstCalculationMethod;
          discount_settings?: Json;
          inventory_settings?: Json;
          sales_settings?: Json;
          pos_settings?: Json;
        };
        Relationships: [];
      };
      employees: {
        Row: {
          id: string;
          store_user_id: string;
          store_id: string;
          employee_code: string;
          first_name: string;
          middle_name: string | null;
          last_name: string;
          full_name: string;
          email: string;
          phone: string;
          alternate_email: string | null;
          alternate_phone: string | null;
          whatsapp_number: string | null;
          date_of_birth: string | null;
          gender: GenderType | null;
          blood_group: BloodGroupType | null;
          marital_status: MaritalStatusType | null;
          nationality: string | null;
          current_address_line1: string | null;
          current_address_line2: string | null;
          current_city: string | null;
          current_state: string | null;
          current_pincode: string | null;
          current_country: string | null;
          permanent_address_line1: string | null;
          permanent_address_line2: string | null;
          permanent_city: string | null;
          permanent_state: string | null;
          permanent_pincode: string | null;
          permanent_country: string | null;
          same_as_current: boolean;
          aadhar_number: string | null;
          pan_number: string | null;
          uan_number: string | null;
          esic_number: string | null;
          driving_license: string | null;
          passport_number: string | null;
          voter_id: string | null;
          employee_type: EmployeeType;
          employment_status: EmploymentStatus;
          joining_date: string;
          confirmation_date: string | null;
          probation_period_months: number;
          probation_end_date: string | null;
          resignation_date: string | null;
          last_working_date: string | null;
          termination_date: string | null;
          termination_reason: string | null;
          notice_period_days: number;
          salary: number | null;
          pay_frequency: PayFrequency;
          bank_name: string | null;
          bank_account_number: string | null;
          ifsc_code: string | null;
          bank_branch: string | null;
          pf_account_number: string | null;
          profile_picture: string | null;
          qualification: string | null;
          specialization: string | null;
          experience_years: number | null;
          previous_employer: string | null;
          skills: string[] | null;
          certifications: Json | null;
          documents: Json | null;
          performance_rating: number | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          emergency_contact_relation: string | null;
          notes: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          store_user_id: string;
          store_id: string;
          employee_code: string;
          first_name: string;
          middle_name?: string | null;
          last_name: string;
          full_name: string;
          email: string;
          phone: string;
          alternate_email?: string | null;
          alternate_phone?: string | null;
          whatsapp_number?: string | null;
          date_of_birth?: string | null;
          gender?: GenderType | null;
          blood_group?: BloodGroupType | null;
          marital_status?: MaritalStatusType | null;
          nationality?: string | null;
          employee_type?: EmployeeType;
          employment_status?: EmploymentStatus;
          joining_date: string;
          confirmation_date?: string | null;
          probation_period_months?: number;
          notice_period_days?: number;
          salary?: number | null;
          pay_frequency?: PayFrequency;
          bank_name?: string | null;
          bank_account_number?: string | null;
          ifsc_code?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          first_name?: string;
          middle_name?: string | null;
          last_name?: string;
          full_name?: string;
          email?: string;
          phone?: string;
          alternate_email?: string | null;
          alternate_phone?: string | null;
          date_of_birth?: string | null;
          gender?: GenderType | null;
          blood_group?: BloodGroupType | null;
          marital_status?: MaritalStatusType | null;
          employee_type?: EmployeeType;
          employment_status?: EmploymentStatus;
          salary?: number | null;
          pay_frequency?: PayFrequency;
          bank_name?: string | null;
          bank_account_number?: string | null;
          ifsc_code?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      invitations: {
        Row: {
          id: string;
          store_id: string;
          role_id: string;
          email: string;
          token: string;
          status: InvitationStatus;
          expires_at: string;
          accepted_at: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          role_id: string;
          email: string;
          token?: string;
          status?: InvitationStatus;
          expires_at: string;
          accepted_at?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          status?: InvitationStatus;
          accepted_at?: string | null;
        };
        Relationships: [];
      };
      // ====================================================================
      // PHASE 2: SUPPLIER & INVENTORY TABLES
      // ====================================================================
      suppliers: {
        Row: {
          id: string;
          store_id: string;
          supplier_code: string;
          name: string;
          legal_name: string | null;
          type: string;
          gstin: string | null;
          pan_number: string | null;
          tan_number: string | null;
          msme_number: string | null;
          contact_person: string | null;
          email: string | null;
          phone: string | null;
          alternate_phone: string | null;
          whatsapp: string | null;
          address_line1: string | null;
          address_line2: string | null;
          landmark: string | null;
          city: string | null;
          state: string | null;
          pincode: string | null;
          country: string;
          bank_name: string | null;
          bank_account_number: string | null;
          ifsc_code: string | null;
          bank_branch: string | null;
          upi_id: string | null;
          payment_terms: string;
          credit_limit: number | null;
          credit_days: number;
          default_discount_percentage: number;
          tax_inclusive: boolean;
          is_active: boolean;
          is_preferred: boolean;
          blacklisted: boolean;
          blacklist_reason: string | null;
          website: string | null;
          notes: string | null;
          tags: string[] | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          supplier_code: string;
          name: string;
          legal_name?: string | null;
          type?: string;
          gstin?: string | null;
          pan_number?: string | null;
          tan_number?: string | null;
          msme_number?: string | null;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          whatsapp?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          landmark?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          country?: string;
          bank_name?: string | null;
          bank_account_number?: string | null;
          ifsc_code?: string | null;
          bank_branch?: string | null;
          upi_id?: string | null;
          payment_terms?: string;
          credit_limit?: number | null;
          credit_days?: number;
          default_discount_percentage?: number;
          tax_inclusive?: boolean;
          is_active?: boolean;
          is_preferred?: boolean;
          blacklisted?: boolean;
          blacklist_reason?: string | null;
          website?: string | null;
          notes?: string | null;
          tags?: string[] | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          supplier_code?: string;
          name?: string;
          legal_name?: string | null;
          type?: string;
          gstin?: string | null;
          pan_number?: string | null;
          tan_number?: string | null;
          msme_number?: string | null;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          whatsapp?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          landmark?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          country?: string;
          bank_name?: string | null;
          bank_account_number?: string | null;
          ifsc_code?: string | null;
          bank_branch?: string | null;
          upi_id?: string | null;
          payment_terms?: string;
          credit_limit?: number | null;
          credit_days?: number;
          default_discount_percentage?: number;
          tax_inclusive?: boolean;
          is_active?: boolean;
          is_preferred?: boolean;
          blacklisted?: boolean;
          blacklist_reason?: string | null;
          website?: string | null;
          notes?: string | null;
          tags?: string[] | null;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      supplier_contacts: {
        Row: {
          id: string;
          supplier_id: string;
          name: string;
          designation: string | null;
          department: string | null;
          email: string | null;
          phone: string | null;
          alternate_phone: string | null;
          is_primary: boolean;
          is_authorized: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          name: string;
          designation?: string | null;
          department?: string | null;
          email?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          is_primary?: boolean;
          is_authorized?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          name?: string;
          designation?: string | null;
          department?: string | null;
          email?: string | null;
          phone?: string | null;
          alternate_phone?: string | null;
          is_primary?: boolean;
          is_authorized?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      supplier_products: {
        Row: {
          id: string;
          supplier_id: string;
          product_id: string;
          store_id: string;
          supplier_product_code: string | null;
          supplier_product_name: string | null;
          purchase_price: number;
          mrp: number | null;
          discount_percentage: number;
          lead_time_days: number | null;
          minimum_order_quantity: number;
          is_preferred: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          product_id: string;
          store_id: string;
          supplier_product_code?: string | null;
          supplier_product_name?: string | null;
          purchase_price: number;
          mrp?: number | null;
          discount_percentage?: number;
          lead_time_days?: number | null;
          minimum_order_quantity?: number;
          is_preferred?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          supplier_product_code?: string | null;
          supplier_product_name?: string | null;
          purchase_price?: number;
          mrp?: number | null;
          discount_percentage?: number;
          lead_time_days?: number | null;
          minimum_order_quantity?: number;
          is_preferred?: boolean;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      // ======================================================================
      // PRODUCT CATALOG TABLES (migration: 5_inventory_supplier.sql)
      // ======================================================================
      units_of_measure: {
        Row: {
          id: string;
          store_id: string;
          name: string;
          code: string;
          symbol: string | null;
          category: string | null;
          is_base_unit: boolean;
          base_unit_id: string | null;
          conversion_factor: number | null;
          decimal_places: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          name: string;
          code: string;
          symbol?: string | null;
          category?: string | null;
          is_base_unit?: boolean;
          base_unit_id?: string | null;
          conversion_factor?: number | null;
          decimal_places?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          name?: string;
          code?: string;
          symbol?: string | null;
          category?: string | null;
          is_base_unit?: boolean;
          base_unit_id?: string | null;
          conversion_factor?: number | null;
          decimal_places?: number;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          store_id: string;
          name: string;
          code: string | null;
          description: string | null;
          parent_id: string | null;
          level: number;
          path: string | null;
          sort_order: number;
          icon: string | null;
          image_url: string | null;
          is_active: boolean;
          is_leaf: boolean;
          metadata: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          name: string;
          code?: string | null;
          description?: string | null;
          parent_id?: string | null;
          level?: number;
          path?: string | null;
          sort_order?: number;
          icon?: string | null;
          image_url?: string | null;
          is_active?: boolean;
          is_leaf?: boolean;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          name?: string;
          code?: string | null;
          description?: string | null;
          parent_id?: string | null;
          level?: number;
          path?: string | null;
          sort_order?: number;
          icon?: string | null;
          image_url?: string | null;
          is_active?: boolean;
          is_leaf?: boolean;
          metadata?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      products: {
        Row: {
          id: string;
          store_id: string;
          product_code: string;
          barcode: string | null;
          alternate_barcodes: string[] | null;
          name: string;
          description: string | null;
          short_description: string | null;
          category_id: string | null;
          brand: string | null;
          model: string | null;
          hsn_code: string | null;
          gst_percentage: number;
          cess_percentage: number;
          mrp: number;
          selling_price: number;
          purchase_price: number | null;
          average_cost: number | null;
          unit_id: string | null;
          minimum_stock: number;
          reorder_level: number;
          is_batch_tracked: boolean;
          is_active: boolean;
          is_taxable: boolean;
          primary_image: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          product_code: string;
          barcode?: string | null;
          alternate_barcodes?: string[] | null;
          name: string;
          description?: string | null;
          short_description?: string | null;
          category_id?: string | null;
          brand?: string | null;
          model?: string | null;
          hsn_code?: string | null;
          gst_percentage?: number;
          cess_percentage?: number;
          mrp: number;
          selling_price: number;
          purchase_price?: number | null;
          average_cost?: number | null;
          unit_id?: string | null;
          minimum_stock?: number;
          reorder_level?: number;
          is_batch_tracked?: boolean;
          is_active?: boolean;
          is_taxable?: boolean;
          primary_image?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          product_code?: string;
          barcode?: string | null;
          alternate_barcodes?: string[] | null;
          name?: string;
          description?: string | null;
          short_description?: string | null;
          category_id?: string | null;
          brand?: string | null;
          model?: string | null;
          hsn_code?: string | null;
          gst_percentage?: number;
          cess_percentage?: number;
          mrp?: number;
          selling_price?: number;
          purchase_price?: number | null;
          average_cost?: number | null;
          unit_id?: string | null;
          minimum_stock?: number;
          reorder_level?: number;
          is_batch_tracked?: boolean;
          is_active?: boolean;
          is_taxable?: boolean;
          primary_image?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_barcodes: {
        Row: {
          id: string;
          product_id: string;
          store_id: string;
          barcode: string;
          barcode_type: string;
          price_type: string;
          is_primary: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          store_id: string;
          barcode: string;
          barcode_type?: string;
          price_type?: string;
          is_primary?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          barcode?: string;
          barcode_type?: string;
          price_type?: string;
          is_primary?: boolean;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_variants: {
        Row: {
          id: string;
          product_id: string;
          store_id: string;
          variant_code: string;
          barcode: string | null;
          name: string | null;
          attributes: Json;
          mrp: number | null;
          selling_price: number | null;
          is_active: boolean;
          is_default: boolean;
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          store_id: string;
          variant_code: string;
          barcode?: string | null;
          name?: string | null;
          attributes?: Json;
          mrp?: number | null;
          selling_price?: number | null;
          is_active?: boolean;
          is_default?: boolean;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          variant_code?: string;
          barcode?: string | null;
          name?: string | null;
          attributes?: Json;
          mrp?: number | null;
          selling_price?: number | null;
          is_active?: boolean;
          is_default?: boolean;
          image_url?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory: {
        Row: {
          id: string;
          store_id: string;
          product_id: string;
          variant_id: string | null;
          quantity_on_hand: number;
          quantity_committed: number;
          quantity_available: number;
          quantity_in_transit: number;
          reorder_point: number;
          maximum_stock: number | null;
          location: string | null;
          warehouse: string | null;
          last_counted_at: string | null;
          last_counted_by: string | null;
          last_updated_at: string;
          average_cost: number | null;
          total_value: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          product_id: string;
          variant_id?: string | null;
          quantity_on_hand?: number;
          quantity_committed?: number;
          quantity_in_transit?: number;
          reorder_point?: number;
          maximum_stock?: number | null;
          location?: string | null;
          warehouse?: string | null;
          last_counted_at?: string | null;
          last_counted_by?: string | null;
          last_updated_at?: string;
          average_cost?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          quantity_on_hand?: number;
          quantity_committed?: number;
          quantity_in_transit?: number;
          reorder_point?: number;
          maximum_stock?: number | null;
          location?: string | null;
          warehouse?: string | null;
          last_counted_at?: string | null;
          last_counted_by?: string | null;
          last_updated_at?: string;
          average_cost?: number | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory_transactions: {
        Row: {
          id: string;
          store_id: string;
          product_id: string;
          variant_id: string | null;
          transaction_type: string;
          transaction_date: string;
          quantity: number;
          previous_quantity: number | null;
          new_quantity: number | null;
          unit_cost: number | null;
          total_cost: number | null;
          reference_type: string | null;
          reference_id: string | null;
          reference_number: string | null;
          batch_number: string | null;
          serial_number: string | null;
          expiry_date: string | null;
          manufacturing_date: string | null;
          reason: string | null;
          from_location: string | null;
          to_location: string | null;
          performed_by: string | null;
          notes: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          product_id: string;
          variant_id?: string | null;
          transaction_type: string;
          transaction_date?: string;
          quantity: number;
          previous_quantity?: number | null;
          new_quantity?: number | null;
          unit_cost?: number | null;
          total_cost?: number | null;
          reference_type?: string | null;
          reference_id?: string | null;
          reference_number?: string | null;
          batch_number?: string | null;
          serial_number?: string | null;
          expiry_date?: string | null;
          manufacturing_date?: string | null;
          reason?: string | null;
          from_location?: string | null;
          to_location?: string | null;
          performed_by?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      product_batches: {
        Row: {
          id: string;
          store_id: string;
          product_id: string;
          batch_number: string;
          manufacturing_date: string | null;
          expiry_date: string;
          mrp: number | null;
          initial_quantity: number;
          current_quantity: number;
          purchase_date: string | null;
          purchase_price: number | null;
          supplier_id: string | null;
          purchase_invoice: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          product_id: string;
          batch_number: string;
          manufacturing_date?: string | null;
          expiry_date: string;
          mrp?: number | null;
          initial_quantity: number;
          current_quantity: number;
          purchase_date?: string | null;
          purchase_price?: number | null;
          supplier_id?: string | null;
          purchase_invoice?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          manufacturing_date?: string | null;
          expiry_date?: string;
          mrp?: number | null;
          current_quantity?: number;
          purchase_price?: number | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      price_history: {
        Row: {
          id: string;
          store_id: string;
          product_id: string;
          variant_id: string | null;
          price_type: string;
          old_price: number | null;
          new_price: number | null;
          reason: string | null;
          effective_from: string;
          changed_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          product_id: string;
          variant_id?: string | null;
          price_type: string;
          old_price?: number | null;
          new_price?: number | null;
          reason?: string | null;
          effective_from?: string;
          changed_by?: string | null;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      stock_alerts: {
        Row: {
          id: string;
          store_id: string;
          product_id: string | null;
          batch_id: string | null;
          alert_type: string;
          severity: string;
          current_quantity: number | null;
          threshold_quantity: number | null;
          expiry_date: string | null;
          is_resolved: boolean;
          resolved_at: string | null;
          resolved_by: string | null;
          resolution_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          product_id?: string | null;
          batch_id?: string | null;
          alert_type: string;
          severity?: string;
          current_quantity?: number | null;
          threshold_quantity?: number | null;
          expiry_date?: string | null;
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          is_resolved?: boolean;
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      // ======================================================================
      // PURCHASE TABLES (migration: 6_purchase_orders.sql or similar)
      // ======================================================================
      purchase_orders: {
        Row: {
          id: string;
          store_id: string;
          po_number: string;
          invoice_number: string | null;
          reference_number: string | null;
          supplier_id: string;
          supplier_name: string;
          supplier_gstin: string | null;
          order_date: string;
          expected_delivery_date: string | null;
          received_date: string | null;
          invoice_date: string | null;
          status: string;
          subtotal: number;
          discount_amount: number;
          discount_percentage: number;
          taxable_amount: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          cess_amount: number;
          total_tax: number;
          shipping_charges: number;
          other_charges: number;
          round_off: number;
          grand_total: number;
          payment_status: string;
          paid_amount: number;
          due_amount: number;
          payment_due_date: string | null;
          is_inter_state: boolean;
          place_of_supply: string | null;
          receiving_warehouse: string | null;
          receiving_notes: string | null;
          approved_by: string | null;
          approved_at: string | null;
          cancelled_by: string | null;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          notes: string | null;
          terms_and_conditions: string | null;
          internal_notes: string | null;
          tags: string[] | null;
          metadata: Json;
          attachment_urls: string[] | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          po_number?: string;
          invoice_number?: string | null;
          reference_number?: string | null;
          supplier_id: string;
          supplier_name: string;
          supplier_gstin?: string | null;
          order_date?: string;
          expected_delivery_date?: string | null;
          received_date?: string | null;
          invoice_date?: string | null;
          status?: string;
          subtotal?: number;
          discount_amount?: number;
          discount_percentage?: number;
          taxable_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          cess_amount?: number;
          total_tax?: number;
          shipping_charges?: number;
          other_charges?: number;
          round_off?: number;
          grand_total?: number;
          payment_status?: string;
          paid_amount?: number;
          due_amount?: number;
          payment_due_date?: string | null;
          is_inter_state?: boolean;
          place_of_supply?: string | null;
          receiving_warehouse?: string | null;
          receiving_notes?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          notes?: string | null;
          terms_and_conditions?: string | null;
          internal_notes?: string | null;
          tags?: string[] | null;
          metadata?: Json;
          attachment_urls?: string[] | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          invoice_number?: string | null;
          reference_number?: string | null;
          expected_delivery_date?: string | null;
          received_date?: string | null;
          invoice_date?: string | null;
          status?: string;
          subtotal?: number;
          discount_amount?: number;
          discount_percentage?: number;
          taxable_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          cess_amount?: number;
          total_tax?: number;
          shipping_charges?: number;
          other_charges?: number;
          round_off?: number;
          grand_total?: number;
          payment_status?: string;
          paid_amount?: number;
          due_amount?: number;
          payment_due_date?: string | null;
          is_inter_state?: boolean;
          place_of_supply?: string | null;
          receiving_warehouse?: string | null;
          receiving_notes?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          notes?: string | null;
          terms_and_conditions?: string | null;
          internal_notes?: string | null;
          tags?: string[] | null;
          metadata?: Json;
          attachment_urls?: string[] | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      purchase_order_items: {
        Row: {
          id: string;
          purchase_order_id: string;
          store_id: string;
          product_id: string;
          variant_id: string | null;
          product_name: string;
          product_code: string;
          barcode: string | null;
          hsn_code: string | null;
          unit_id: string | null;
          unit_code: string | null;
          ordered_quantity: number;
          received_quantity: number;
          returned_quantity: number;
          pending_quantity: number;
          unit_price: number;
          mrp: number | null;
          discount_percentage: number;
          discount_amount: number;
          line_total: number;
          gst_percentage: number;
          cgst_percentage: number;
          sgst_percentage: number;
          igst_percentage: number;
          cess_percentage: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          cess_amount: number;
          tax_amount: number;
          total_amount: number;
          batch_number: string | null;
          manufacturing_date: string | null;
          expiry_date: string | null;
          item_status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          purchase_order_id: string;
          store_id: string;
          product_id: string;
          variant_id?: string | null;
          product_name: string;
          product_code: string;
          barcode?: string | null;
          hsn_code?: string | null;
          unit_id?: string | null;
          unit_code?: string | null;
          ordered_quantity: number;
          received_quantity?: number;
          returned_quantity?: number;
          pending_quantity?: number;
          unit_price: number;
          mrp?: number | null;
          discount_percentage?: number;
          discount_amount?: number;
          line_total: number;
          gst_percentage?: number;
          cgst_percentage?: number;
          sgst_percentage?: number;
          igst_percentage?: number;
          cess_percentage?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          cess_amount?: number;
          tax_amount?: number;
          total_amount: number;
          batch_number?: string | null;
          manufacturing_date?: string | null;
          expiry_date?: string | null;
          item_status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          received_quantity?: number;
          returned_quantity?: number;
          pending_quantity?: number;
          unit_price?: number;
          discount_percentage?: number;
          discount_amount?: number;
          line_total?: number;
          tax_amount?: number;
          total_amount?: number;
          item_status?: string;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      purchase_payments: {
        Row: {
          id: string;
          purchase_order_id: string;
          store_id: string;
          payment_number: string;
          payment_date: string;
          amount: number;
          payment_method: string;
          transaction_reference: string | null;
          bank_name: string | null;
          cheque_number: string | null;
          cheque_date: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          purchase_order_id: string;
          store_id: string;
          payment_number?: string;
          payment_date?: string;
          amount: number;
          payment_method: string;
          transaction_reference?: string | null;
          bank_name?: string | null;
          cheque_number?: string | null;
          cheque_date?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          status?: string;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      purchase_returns: {
        Row: {
          id: string;
          purchase_order_id: string;
          store_id: string;
          return_number: string;
          debit_note_number: string | null;
          supplier_id: string;
          supplier_name: string;
          return_date: string;
          subtotal: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          cess_amount: number;
          total_tax: number;
          grand_total: number;
          status: string;
          reason: string;
          refund_status: string;
          refund_amount: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          purchase_order_id: string;
          store_id: string;
          return_number?: string;
          debit_note_number?: string | null;
          supplier_id: string;
          supplier_name: string;
          return_date?: string;
          subtotal?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          cess_amount?: number;
          total_tax?: number;
          grand_total?: number;
          status?: string;
          reason: string;
          refund_status?: string;
          refund_amount?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          status?: string;
          refund_status?: string;
          refund_amount?: number;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      purchase_return_items: {
        Row: {
          id: string;
          purchase_return_id: string;
          purchase_order_item_id: string | null;
          store_id: string;
          product_id: string;
          variant_id: string | null;
          product_name: string;
          product_code: string;
          hsn_code: string | null;
          return_quantity: number;
          unit_price: number;
          gst_percentage: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          cess_amount: number;
          tax_amount: number;
          line_total: number;
          total_amount: number;
          batch_number: string | null;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          purchase_return_id: string;
          purchase_order_item_id?: string | null;
          store_id: string;
          product_id: string;
          variant_id?: string | null;
          product_name: string;
          product_code: string;
          hsn_code?: string | null;
          return_quantity: number;
          unit_price: number;
          gst_percentage?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          cess_amount?: number;
          tax_amount?: number;
          line_total: number;
          total_amount: number;
          batch_number?: string | null;
          reason?: string | null;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
    };
    Views: {
      v_user_store_role: {
        Row: {
          store_user_id: string;
          user_id: string;
          email: string;
          full_name: string | null;
          store_id: string;
          store_name: string;
          store_code: string;
          store_status: StoreStatus;
          organization_id: string;
          organization_name: string;
          role_id: string;
          role_name: RoleName;
          role_display_name: string;
          permissions: Json;
          is_active: boolean;
          is_banned: boolean;
          last_login_at: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_super_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      get_user_store: {
        Args: Record<string, never>;
        Returns: string | null;
      };
      get_user_role: {
        Args: { p_store_id?: string };
        Returns: string | null;
      };
      has_permission: {
        Args: { p_permission: string; p_store_id?: string };
        Returns: boolean;
      };
      is_ip_whitelisted: {
        Args: { p_store_id: string; p_ip: string };
        Returns: boolean;
      };
      can_access_store: {
        Args: { p_store_id: string };
        Returns: boolean;
      };
      get_user_organization: {
        Args: Record<string, never>;
        Returns: string | null;
      };
      is_store_owner: {
        Args: { p_store_id: string };
        Returns: boolean;
      };
      login_user: {
        Args: {
          p_email: string;
          p_ip: string;
          p_user_agent?: string;
          p_device_info?: Json;
        };
        Returns: Json;
      };
      get_purchase_dashboard_stats: {
        Args: { p_store_id: string };
        Returns: Json;
      };
      get_supplier_purchase_summary: {
        Args: { p_store_id: string; p_supplier_id: string };
        Returns: Json;
      };
    };
    Enums: {
      registration_type: RegistrationType;
      store_type: StoreType;
      store_status: StoreStatus;
      role_name: RoleName;
      employee_type: EmployeeType;
      employment_status: EmploymentStatus;
      pay_frequency: PayFrequency;
      whitelist_purpose: WhitelistPurpose;
      gst_status: GstStatus;
      tax_payer_type: TaxPayerType;
      hsn_type: HsnType;
      invitation_status: InvitationStatus;
      gender_type: GenderType;
      blood_group_type: BloodGroupType;
      marital_status_type: MaritalStatusType;
      gst_calculation_method: GstCalculationMethod;
    };
    CompositeTypes: Record<string, never>;
  };
}

// ============================================================================
// Enum Types
// ============================================================================

export type RegistrationType = "private_limited" | "partnership" | "proprietorship" | "llp" | "public_limited" | "other";
export type StoreType = "retail" | "warehouse" | "franchise" | "outlet" | "kiosk";
export type StoreStatus = "pending" | "active" | "suspended" | "rejected" | "closed";
export type RoleName = "super_admin" | "store_admin" | "manager" | "cashier" | "accountant" | "inventory_manager";
export type EmployeeType = "full_time" | "part_time" | "contractor" | "intern" | "trainee";
export type EmploymentStatus = "active" | "probation" | "notice_period" | "terminated" | "resigned" | "absconded";
export type PayFrequency = "monthly" | "weekly" | "daily" | "hourly";
export type WhitelistPurpose = "pos_terminal" | "admin_access" | "api_access" | "backup_system" | "mobile_app";
export type GstStatus = "active" | "suspended" | "cancelled" | "migrated";
export type TaxPayerType = "regular" | "composition" | "casual" | "non_resident" | "sez";
export type HsnType = "hsn" | "sac";
export type InvitationStatus = "pending" | "accepted" | "expired" | "cancelled" | "bounced";
export type GenderType = "male" | "female" | "other" | "prefer_not_to_say";
export type BloodGroupType = "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";
export type MaritalStatusType = "single" | "married" | "divorced" | "widowed" | "separated";
export type GstCalculationMethod = "inclusive" | "exclusive";
