import {
  LayoutDashboard,
  ShoppingCart,
  Users,
  Package,
  BarChart3,
  Settings,
  Building2,
  Shield,
  UserCog,
  Receipt,
  TrendingUp,
  FileText,
  Boxes,
  Truck,
  ClipboardList,
  DollarSign,
  CreditCard,
  UserCheck,
  Store,
  Activity,
  Wallet,
  ArrowLeftRight,
  PackageSearch,
  AlertTriangle,
  Globe,
  Lock,
  Bell,
  HelpCircle,
  Zap,
  ShoppingBag,
  Cpu,
} from "lucide-react";
import type { SearchItem } from "../types";

// ============================================================================
// Search Index — All searchable pages/actions in the platform
// Filtered at runtime by user role and permissions
// ============================================================================

export const SEARCH_INDEX: SearchItem[] = [
  // ── Navigation / Dashboards ──────────────────────────────────────────────
  {
    id: "nav-super-admin-dashboard",
    name: "Super Admin Dashboard",
    description: "Platform-wide administration and system overview",
    category: "navigation",
    icon: Shield,
    href: "/super-admin/dashboard",
    keywords: ["admin", "platform", "system", "overview", "dashboard"],
    priority: "high",
    roles: ["super_admin"],
    shortcut: "Alt+D",
  },
  {
    id: "nav-store-admin-dashboard",
    name: "Store Admin Dashboard",
    description: "Manage your store, staff, and view analytics",
    category: "navigation",
    icon: Store,
    href: "/store-admin/dashboard",
    keywords: ["store", "admin", "management", "dashboard", "analytics"],
    priority: "high",
    roles: ["store_admin", "super_admin"],
    shortcut: "Alt+D",
  },
  {
    id: "nav-manager-dashboard",
    name: "Manager Dashboard",
    description: "Oversee store operations and team performance",
    category: "navigation",
    icon: Activity,
    href: "/manager/dashboard",
    keywords: ["manager", "operations", "team", "performance", "dashboard"],
    priority: "high",
    roles: ["manager", "store_admin", "super_admin"],
    shortcut: "Alt+D",
  },
  {
    id: "nav-pos",
    name: "Point of Sale",
    description: "Open the POS register to process sales",
    category: "navigation",
    icon: ShoppingCart,
    href: "/pos",
    keywords: ["pos", "sale", "register", "checkout", "transaction", "billing"],
    priority: "high",
    roles: ["cashier", "manager", "store_admin", "super_admin"],
    shortcut: "Alt+P",
  },
  {
    id: "nav-purchases",
    name: "Purchases",
    description: "Create and manage supplier purchase entries",
    category: "navigation",
    icon: ShoppingBag,
    href: "/store-admin/purchase",
    keywords: [
      "purchase",
      "buy",
      "supplier order",
      "stock entry",
      "inventory purchase",
      "grn"
    ],
    priority: "high",
    roles: ["store_admin", "super_admin"],
    shortcut: "Alt+U", // U = pUrchase (since P is used for POS)
  },
  {
    id: "nav-accountant-dashboard",
    name: "Accountant Dashboard",
    description: "Manage finances and generate financial reports",
    category: "navigation",
    icon: DollarSign,
    href: "/accountant/dashboard",
    keywords: ["accountant", "finance", "money", "dashboard"],
    priority: "high",
    roles: ["accountant", "store_admin", "super_admin"],
    shortcut: "Alt+F",
  },
  {
    id: "nav-inventory-dashboard",
    name: "Inventory Dashboard",
    description: "Manage stock levels and inventory operations",
    category: "navigation",
    icon: Package,
    href: "/inventory/dashboard",
    keywords: ["inventory", "stock", "warehouse", "products", "dashboard"],
    priority: "high",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    shortcut: "Alt+I",
  },

  // ── Sales & POS ─────────────────────────────────────────────────────────
  {
    id: "sales-new-sale",
    name: "New Sale",
    description: "Start a new sales transaction",
    category: "sales",
    icon: ShoppingCart,
    href: "/pos",
    keywords: ["new", "sale", "transaction", "checkout", "bill", "invoice"],
    priority: "high",
    roles: ["cashier", "manager", "store_admin", "super_admin"],
    shortcut: "Alt+S",
  },
  {
    id: "sales-orders",
    name: "View Orders",
    description: "Browse and manage all orders",
    category: "sales",
    icon: Receipt,
    href: "/pos/orders",
    keywords: ["orders", "history", "transactions", "receipts"],
    priority: "medium",
    roles: ["cashier", "manager", "store_admin", "super_admin"],
    shortcut: "Alt+O",
  },
  {
    id: "sales-refunds",
    name: "Process Refund",
    description: "Process a customer refund or return",
    category: "sales",
    icon: ArrowLeftRight,
    href: "/pos/refunds",
    keywords: ["refund", "return", "exchange", "cancel"],
    priority: "medium",
    roles: ["manager", "store_admin", "super_admin"],
    permissions: ["process_refunds"],
    shortcut: "Alt+R",
  },
  {
    id: "sales-daily-report",
    name: "Daily Sales Report",
    description: "View today's sales summary and statistics",
    category: "sales",
    icon: FileText,
    href: "/pos/daily-report",
    keywords: ["daily", "report", "today", "summary", "sales"],
    priority: "medium",
    roles: ["cashier", "manager", "store_admin", "super_admin"],
  },

  // ── Employee Management ──────────────────────────────────────────────────
  {
    id: "emp-all-employees",
    name: "All Employees",
    description: "View and manage all store employees",
    category: "employees",
    icon: Users,
    href: "/store-admin/employees",
    keywords: ["employees", "staff", "team", "workers", "people"],
    priority: "high",
    roles: ["store_admin", "super_admin", "manager"],
    permissions: ["manage_employees"],
    shortcut: "Alt+E",
  },
  {
    id: "emp-roles-permissions",
    name: "Roles & Permissions",
    description: "Manage employee roles and access permissions",
    category: "employees",
    icon: UserCog,
    href: "/store-admin/employees/roles",
    keywords: ["roles", "permissions", "access", "security", "authorization"],
    priority: "medium",
    roles: ["store_admin", "super_admin"],
    permissions: ["manage_employees"],
  },
  {
    id: "emp-team-shifts",
    name: "Team Shifts",
    description: "Manage team shift schedules",
    category: "employees",
    icon: Users,
    href: "/manager/team/shifts",
    keywords: ["shifts", "schedule", "roster", "timing", "attendance"],
    priority: "medium",
    roles: ["manager", "store_admin", "super_admin"],
    permissions: ["manage_employees"],
  },

  // ── Inventory ────────────────────────────────────────────────────────────
  {
    id: "inv-all-products",
    name: "All Products",
    description: "Browse and manage your product catalog",
    category: "inventory",
    icon: Boxes,
    href: "/inventory/products",
    keywords: ["products", "catalog", "items", "goods", "merchandise"],
    priority: "high",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    permissions: ["manage_inventory"],
    shortcut: "Alt+G",
  },
  {
    id: "inv-stock-levels",
    name: "Stock Levels",
    description: "Check current stock levels for all products",
    category: "inventory",
    icon: Package,
    href: "/inventory/stock",
    keywords: ["stock", "levels", "quantity", "available", "on-hand"],
    priority: "high",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    permissions: ["view_inventory"],
  },
  {
    id: "inv-low-stock",
    name: "Low Stock Alerts",
    description: "View items that need restocking",
    category: "inventory",
    icon: AlertTriangle,
    href: "/inventory/stock/low",
    keywords: ["low", "stock", "alert", "reorder", "out of stock", "shortage"],
    priority: "high",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    permissions: ["view_inventory"],
    shortcut: "Alt+L",
  },
  {
    id: "inv-purchase-orders",
    name: "Purchase Orders",
    description: "Create and manage purchase orders to suppliers",
    category: "inventory",
    icon: ClipboardList,
    href: "/inventory/purchase-orders",
    keywords: ["purchase", "order", "buy", "procurement", "supplier"],
    priority: "medium",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    permissions: ["manage_inventory"],
  },
  {
    id: "inv-suppliers",
    name: "Suppliers",
    description: "Manage your supplier contacts and information",
    category: "inventory",
    icon: Truck,
    href: "/inventory/suppliers",
    keywords: ["suppliers", "vendors", "providers", "contacts"],
    priority: "medium",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    permissions: ["manage_suppliers"],
    shortcut: "Alt+V",
  },
  {
    id: "inv-physical-count",
    name: "Physical Count",
    description: "Start or manage a physical inventory count",
    category: "inventory",
    icon: PackageSearch,
    href: "/inventory/audits/count",
    keywords: ["count", "physical", "audit", "check", "verify"],
    priority: "medium",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    permissions: ["manage_inventory"],
  },

  // ── Reports ──────────────────────────────────────────────────────────────
  {
    id: "rep-sales-report",
    name: "Sales Report",
    description: "Detailed sales report with trends and breakdowns",
    category: "reports",
    icon: TrendingUp,
    href: "/store-admin/reports/sales",
    keywords: ["sales", "report", "analytics", "trends", "graph"],
    priority: "high",
    roles: ["store_admin", "super_admin", "manager"],
    permissions: ["view_reports"],
    shortcut: "Alt+T",
  },
  {
    id: "rep-revenue-analytics",
    name: "Revenue Analytics",
    description: "In-depth revenue analysis and projections",
    category: "reports",
    icon: BarChart3,
    href: "/store-admin/reports/revenue",
    keywords: ["revenue", "analytics", "income", "earnings", "projections"],
    priority: "medium",
    roles: ["store_admin", "super_admin", "accountant"],
    permissions: ["view_reports"],
  },
  {
    id: "rep-staff-performance",
    name: "Staff Performance",
    description: "Employee performance metrics and reports",
    category: "reports",
    icon: Users,
    href: "/store-admin/reports/staff",
    keywords: ["staff", "performance", "employee", "metrics", "productivity"],
    priority: "medium",
    roles: ["store_admin", "super_admin", "manager"],
    permissions: ["view_reports"],
  },
  {
    id: "rep-income-statement",
    name: "Income Statement",
    description: "Profit & loss statement and income summary",
    category: "reports",
    icon: FileText,
    href: "/accountant/reports/income",
    keywords: ["income", "statement", "profit", "loss", "P&L"],
    priority: "high",
    roles: ["accountant", "store_admin", "super_admin"],
    permissions: ["view_financials"],
  },
  {
    id: "rep-balance-sheet",
    name: "Balance Sheet",
    description: "Assets, liabilities, and equity summary",
    category: "reports",
    icon: FileText,
    href: "/accountant/reports/balance",
    keywords: ["balance", "sheet", "assets", "liabilities", "equity"],
    priority: "medium",
    roles: ["accountant", "store_admin", "super_admin"],
    permissions: ["view_financials"],
  },
  {
    id: "rep-tax-report",
    name: "Tax Report",
    description: "Tax calculations and filing reports",
    category: "reports",
    icon: FileText,
    href: "/accountant/reports/tax",
    keywords: ["tax", "GST", "VAT", "filing", "compliance"],
    priority: "medium",
    roles: ["accountant", "store_admin", "super_admin"],
    permissions: ["view_financials"],
  },
  {
    id: "rep-inventory-valuation",
    name: "Inventory Valuation",
    description: "Current value of all inventory items",
    category: "reports",
    icon: Boxes,
    href: "/inventory/reports/valuation",
    keywords: ["inventory", "valuation", "value", "worth", "cost"],
    priority: "medium",
    roles: ["inventory_manager", "manager", "store_admin", "super_admin"],
    permissions: ["view_reports"],
  },
  {
    id: "rep-audit-logs",
    name: "Audit Logs",
    description: "System activity and change audit trail",
    category: "reports",
    icon: Shield,
    href: "/super-admin/reports/audit",
    keywords: ["audit", "logs", "activity", "trail", "history", "changes"],
    priority: "medium",
    roles: ["super_admin", "store_admin"],
    permissions: ["view_audit_logs"],
  },

  // ── Customers ────────────────────────────────────────────────────────────
  {
    id: "cust-manage",
    name: "Customer Management",
    description: "View and manage customer database",
    category: "customers",
    icon: UserCheck,
    href: "/store-admin/customers",
    keywords: ["customers", "clients", "buyers", "contacts", "CRM"],
    priority: "high",
    roles: ["store_admin", "super_admin", "manager", "cashier"],
    permissions: ["manage_customers"],
    shortcut: "Alt+C",
  },

  // ── Finance ──────────────────────────────────────────────────────────────
  {
    id: "fin-transactions",
    name: "All Transactions",
    description: "View complete transaction history",
    category: "finance",
    icon: CreditCard,
    href: "/accountant/transactions",
    keywords: ["transactions", "payments", "history", "ledger"],
    priority: "high",
    roles: ["accountant", "store_admin", "super_admin"],
    shortcut: "Alt+X",
  },
  {
    id: "fin-expenses",
    name: "Expense Management",
    description: "Record and manage business expenses",
    category: "finance",
    icon: Wallet,
    href: "/accountant/transactions/expenses",
    keywords: ["expenses", "costs", "bills", "spending"],
    priority: "medium",
    roles: ["accountant", "store_admin", "super_admin"],
  },
  {
    id: "fin-invoices",
    name: "Invoice Management",
    description: "Create and manage customer invoices",
    category: "finance",
    icon: FileText,
    href: "/accountant/invoices",
    keywords: ["invoices", "billing", "receipts", "payment"],
    priority: "medium",
    roles: ["accountant", "store_admin", "super_admin"],
  },
  {
    id: "fin-payroll",
    name: "Payroll",
    description: "Manage employee salary and payroll",
    category: "finance",
    icon: Wallet,
    href: "/accountant/payroll",
    keywords: ["payroll", "salary", "wages", "compensation"],
    priority: "medium",
    roles: ["accountant", "store_admin", "super_admin"],
  },

  // ── Settings ─────────────────────────────────────────────────────────────
  {
    id: "set-store-general",
    name: "Store Settings",
    description: "General store configuration and preferences",
    category: "settings",
    icon: Settings,
    href: "/store-admin/settings",
    keywords: ["settings", "configuration", "preferences", "general", "store"],
    priority: "high",
    roles: ["store_admin", "super_admin"],
    permissions: ["manage_store_settings"],
    shortcut: "Alt+,",
  },
  {
    id: "set-store-security",
    name: "Security Settings",
    description: "Manage store security and access controls",
    category: "settings",
    icon: Lock,
    href: "/store-admin/settings/security",
    keywords: ["security", "password", "access", "control", "lock"],
    priority: "medium",
    roles: ["store_admin", "super_admin"],
    permissions: ["manage_store_settings"],
  },
  {
    id: "set-ip-whitelist",
    name: "IP Whitelist",
    description: "Manage allowed IP addresses for store access",
    category: "settings",
    icon: Globe,
    href: "/store-admin/settings/ip-whitelist",
    keywords: ["IP", "whitelist", "network", "access", "firewall"],
    priority: "low",
    roles: ["store_admin", "super_admin"],
    permissions: ["manage_ip_whitelist"],
  },
  {
    id: "set-hardware",
    name: "Hardware Settings",
    description: "Manage barcode scanners, receipt printers, and POS hardware",
    category: "settings",
    icon: Cpu,
    href: "/store-admin/settings/hardware",
    keywords: [
      "hardware",
      "scanner",
      "barcode",
      "printer",
      "receipt",
      "thermal",
      "USB",
      "device",
      "POS hardware",
    ],
    priority: "high",
    roles: ["store_admin", "super_admin", "cashier", "manager"],
    shortcut: "Alt+H",
  },
  {
    id: "set-profile",
    name: "My Profile",
    description: "View and edit your personal profile",
    category: "settings",
    icon: UserCheck,
    href: "/profile",
    keywords: ["profile", "account", "personal", "me", "my"],
    priority: "medium",
    roles: ["super_admin", "store_admin", "manager", "cashier", "accountant", "inventory_manager"],
  },
  {
    id: "set-platform",
    name: "Platform Settings",
    description: "Global platform configuration (Super Admin)",
    category: "settings",
    icon: Zap,
    href: "/super-admin/settings",
    keywords: ["platform", "global", "system", "configuration"],
    priority: "high",
    roles: ["super_admin"],
  },
  {
    id: "set-feature-flags",
    name: "Feature Flags",
    description: "Enable or disable platform features",
    category: "settings",
    icon: Zap,
    href: "/super-admin/settings/features",
    keywords: ["features", "flags", "toggle", "enable", "disable"],
    priority: "low",
    roles: ["super_admin"],
  },

  // ── Super Admin Platform ─────────────────────────────────────────────────
  {
    id: "sa-all-stores",
    name: "All Stores",
    description: "View and manage all stores on the platform",
    category: "settings",
    icon: Building2,
    href: "/super-admin/stores",
    keywords: ["stores", "all", "platform", "manage", "list"],
    priority: "high",
    roles: ["super_admin"],
  },
  {
    id: "sa-pending-approvals",
    name: "Pending Store Approvals",
    description: "Review and approve new store registrations",
    category: "settings",
    icon: Store,
    href: "/super-admin/stores/pending",
    keywords: ["pending", "approval", "review", "new", "registration"],
    priority: "high",
    roles: ["super_admin"],
  },
  {
    id: "sa-all-users",
    name: "All Users",
    description: "View and manage all platform users",
    category: "settings",
    icon: Users,
    href: "/super-admin/users",
    keywords: ["users", "all", "platform", "manage"],
    priority: "high",
    roles: ["super_admin"],
  },
  {
    id: "sa-organizations",
    name: "Organizations",
    description: "View and manage all organizations",
    category: "settings",
    icon: Building2,
    href: "/super-admin/organizations",
    keywords: ["organizations", "companies", "businesses"],
    priority: "medium",
    roles: ["super_admin"],
  },
];

// ============================================================================
// Search Category Labels
// ============================================================================

export const SEARCH_CATEGORY_LABELS: Record<string, string> = {
  navigation: "Pages",
  sales: "Sales & POS",
  inventory: "Inventory",
  employees: "Employees",
  reports: "Reports",
  settings: "Settings",
  customers: "Customers",
  finance: "Finance",
};

// ============================================================================
// Priority Weights (for ranking)
// ============================================================================

export const PRIORITY_WEIGHTS: Record<string, number> = {
  high: 3,
  medium: 2,
  low: 1,
};
